/**
 * Turns the raw project photos in ../ into responsive AVIF/WebP sets plus a
 * generated manifest (dimensions + LQIP) that the app imports at build time.
 * Run with `npm run media` whenever new source photos land in the repo root.
 */
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { join, parse } from 'node:path';
import sharp from 'sharp';

const SRC = new URL('../../', import.meta.url).pathname;
const OUT = new URL('../public/media/', import.meta.url).pathname;
const WIDTHS = [480, 768, 1200, 1800];

await mkdir(OUT, { recursive: true });

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f));
const manifest = {};

for (const file of files) {
  const slug = parse(file).name;
  const input = sharp(join(SRC, file)).rotate();
  const { width, height } = await input.metadata();

  const widths = WIDTHS.filter((w) => w <= width);
  if (!widths.includes(width) && widths.length < WIDTHS.length) widths.push(width);

  for (const w of widths) {
    const resized = sharp(join(SRC, file)).rotate().resize({ width: w, withoutEnlargement: true });
    await resized.clone().avif({ quality: 55, effort: 3 }).toFile(join(OUT, `${slug}-${w}.avif`));
    await resized.clone().webp({ quality: 74 }).toFile(join(OUT, `${slug}-${w}.webp`));
  }

  // Tiny blurred base64 used as an inline placeholder while the real file loads.
  const lqip = await sharp(join(SRC, file))
    .rotate()
    .resize({ width: 20 })
    .blur(1.2)
    .webp({ quality: 40 })
    .toBuffer();

  manifest[slug] = {
    width,
    height,
    widths: widths.sort((a, b) => a - b),
    lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
  };
  console.log(`${slug}  ${width}x${height}  →  ${widths.join(', ')}`);
}

await writeFile(
  new URL('../src/content/media.generated.ts', import.meta.url),
  `// AUTO-GENERATED by scripts/prepare-media.mjs — do not edit by hand.\n` +
    `export type MediaEntry = { width: number; height: number; widths: number[]; lqip: string };\n\n` +
    `export const MEDIA_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, MediaEntry>;\n\n` +
    `export type MediaSlug = keyof typeof MEDIA_MANIFEST;\n`,
);

console.log(`\n${files.length} images → ${OUT}`);
