// AUTO-GENERATED by scripts/prepare-media.mjs — do not edit by hand.
export type MediaEntry = { width: number; height: number; widths: number[]; lqip: string };

export const MEDIA_MANIFEST = {
  "ballet": {
    "width": 754,
    "height": 1300,
    "widths": [
      480,
      754
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBQCdASoUACIAPulYqU2pJKQiMBqtUSAdCWUAwNwWTiS9GX4JxP8vlvw2gy2br8fopTvXCMoyAAD+ujfyYbwWAEYNt/n1jZf3DOFCNwXBLsNcWfvYfNuESDg0zhbQxhl/C9vSje69739jLmQcE09Yj5V8Ih/N2VfVm4hCffTExiqJ/YciS88HNoFzvdx9xWmEh08AAAA="
  },
  "black-gold": {
    "width": 1125,
    "height": 1500,
    "widths": [
      480,
      768,
      1125
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoUABsAPu1qqlEppaiiqAqpMB2JaQAAPgBRm/AAAP7wbxvgIPau51D2zM9Ks+/iZTTvfieHwhAAAA=="
  },
  "black-rose": {
    "width": 1900,
    "height": 1267,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JZgCdABjcACr1AFeJWgAA/vK0MIU5GlTaKtijrPBLDFmCzA0lpSf28seD1dlfocAO5codoAH890P+d7H9hU+BmfgAAA=="
  },
  "carnival-hero": {
    "width": 1278,
    "height": 1920,
    "widths": [
      480,
      768,
      1200,
      1278
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUAB4APu1iqE2ppaOiMAgBMB2JZQAAW+i4UPlDoIR3vOi4boAA/vQqb4LNpQWIHb4Bqtd0QuIZUxdS9ooIeXuyQQWgLnGAAAA="
  },
  "crystal": {
    "width": 844,
    "height": 1500,
    "widths": [
      480,
      768,
      844
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwBQCdASoUACQAPu1oq04ppiQiKrgN+TAdiWMAwvhQ4WbhVhM+5vSN6LU0D41bE8lujLM9ona18AD++entABH2CnQP+vrpIF4/poIleANSdRm8Vd44vZxwMlVXV1300VNdYkBm+R1398AmZcJjQNLn4AtQ57wd+DqTS5qT2HoPYCOEP639nQztMJc2TaCwWw8AAA=="
  },
  "fans-stage": {
    "width": 868,
    "height": 1400,
    "widths": [
      480,
      768,
      868
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQBACdASoUACAAPu1oqU+ppiOiKA1RMB2JZQDCgBEZay51pXeZ1I9++JcHXmqrUAD+5S+A3QZOQl50If5IPCAGnJvrxoDz6HIYMt+tyLutgTxocjFejDb3drYyUyjNvurihcuNsgoe80AAAAA="
  },
  "gold-silk": {
    "width": 893,
    "height": 1300,
    "widths": [
      480,
      768,
      893
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwBACdASoUAB0APu1ur1IppiQiqAgBMB2JQBYj4wAfOXRJ9Qs67aAu1mqL/AH2/gAA8cPj01/2HJuwNPkhupt4xSRtNImpPqp+nK7Krs7ufGpxSbCPXxwXnDizDEwlSgjhdW5C2zBvZRSeHPna+nwrQ+D30hQFJzgAAA=="
  },
  "khokhloma": {
    "width": 960,
    "height": 1275,
    "widths": [
      480,
      768,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBQCdASoUABsAPu1iq0+ppSOiMBgIATAdiWUAAC5l1ue4EgGQi+b/cSQ/QhaSbtbQAAD+9FAaa9wGm+dzKDIQDTyvE/4TvabaZwj96R1uqkL+BRzlJYKDaaE3akTZvbecfykbrbeyTDPGSfoylj3Rx2AAAA=="
  },
  "matrix-hero": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200,
      1500
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAwCdASoUABsAPu1krVAtJSQisBgIAaAdiWcAxzAWxNd3ruUAAP7wjHyRoBRlxlndLrIWfz1oAKX6bpgAAA=="
  },
  "matrix-profile": {
    "width": 844,
    "height": 1500,
    "widths": [
      480,
      768,
      844
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBgCdASoUACQAPuVgpk2pJaOiMBqtUSAciWcAygAWbMvVBBs6IvpIoQTQQM+jjUhDCUZBwlt6W1MwAP7w1fSHpXc9HNCzNjxmlLWJd1yJTzUzGpdPTgLKEeWEwh++dYH7/BcSjxpOS/0S1sm9VLO79p9BM4/kJebtdqAXKGZhwYVWHvzBLAAA"
  },
  "matrix-stage": {
    "width": 960,
    "height": 1466,
    "widths": [
      480,
      768,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwBACdASoUAB8APu1orU4ppiSiMAgBMB2JZQC+SB6OCC0ZGm5WOZS5BtPd2k9mPAAA/jFZo3gXQZaWPVbVKdBHFSHr0DBwpAf30aW+pIg4I1527ahbFHn66hZG4/YD9XH9tVzDLlwWN1sDIgAAAA=="
  },
  "new-year": {
    "width": 960,
    "height": 1236,
    "widths": [
      480,
      768,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBQCdASoUABoAPu1qqFAppiOiqA1RMB2JZACdMzQ8n9AAy7zr8kcl1e3SSSiOLAk6PggA/u6MWhXE8FuLdBiOkftdSeRVeNpYJwNBLVF7uCONNlmqTZ6UZKJ10M1dJ6HZ7dAtShacRiSDw0D4h2gcrtD7tKER9NJb2MalnIfatA48G2ysiEPH8Qx9/DRAmKbhD/VAAAA="
  },
  "noir": {
    "width": 960,
    "height": 1175,
    "widths": [
      480,
      768,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAwCdASoUABgAPu1qrlCppaQiqAqpMB2JZwDJEBgPro8AAP7wV2h4o6v2j6MibaMkZ92RhYRY6xd/gAA="
  },
  "red-velvet": {
    "width": 1900,
    "height": 1267,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwBACdASoUAA0APu1iqk2ppaQiMAgBMB2JZACdIFzDFqaxHK34smsntMAA/lVmZKNw6zHuTngVB/TnlFW4oDb7nsOrk+GiB0m+MSOBkMzmur8taCV2RKu5gAA="
  },
  "retro": {
    "width": 865,
    "height": 1300,
    "widths": [
      480,
      768,
      865
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBQCdASoUAB4APuFapk2opSOiN/qoARAcCUAWI9joLgZsluHXldFG/cJdC4Juj+84wAD51qeQTvdyC5M8x0bH9qhwbvWBkI2dNGN18jtwGAF5WP9b/3J0dkf8KewR+Q4i6vIfiJ/6zOt5c8WNOlzkVJR7fpzhAAA="
  },
  "white-ball": {
    "width": 900,
    "height": 1600,
    "widths": [
      480,
      768,
      900
    ],
    "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABwBgCdASoUACQAPu1qrk+ppiQiKqoBMB2JYwC7M8GBcDCSQSYXtTFA0eCzSkoPY4RsE1WoSMBxU+HCt2AA/tqVTED2XJAi3+VHWDvDT5d0BsN0FvfND5uaVXqXddkfJkkral3a/9ZPAkh22imefjvES0Jq4Qq6QqW+YZBPDgMEZmRmm7NxGtrMVi7yPmui7cwgbAq/H44BRbiQH/cAsPGxHdmHkj/KIhA/438qaMGZrNKAAAA="
  }
} as const satisfies Record<string, MediaEntry>;

export type MediaSlug = keyof typeof MEDIA_MANIFEST;
