// AUTO-GENERATED by scripts/prepare-media.mjs — do not edit by hand.
export type MediaEntry = { width: number; height: number; widths: number[]; lqip: string };

export const MEDIA_MANIFEST = {
  "alisa-v-strane-chudes-1": {
    "width": 2000,
    "height": 1333,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JYwAAW+LoZQYvad1LfgD+2r8bKooBkGg/l8iszWoBB3gvLZfAfKAeqG6zhYifG1vXIka+6cNa5AAA"
  },
  "alisa-v-strane-chudes-2": {
    "width": 2000,
    "height": 1333,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQBACdASoUAA0APu1kq04ppaQiMAgBMB2JYwCdMoADTmNmWUZeWHuewAD+5Fjxw7f/BiL9LLWnQAfJyYPm6lr0ObBts7mwG4JK35FBjES42ey4vOAAAA=="
  },
  "apalle-1": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAB4APu1srlIppaQiqAgBMB2JZAAAKY8Nti+jNAhmuFwAAP7p9bbYhdXv64DcmuOqfsO+4SWn3jnqppIU5hk6S12ras7TcMj6QWEEEkEB1TeMEHpXBJN5Sw1d9nUlJyNQAA=="
  },
  "apalle-2": {
    "width": 2000,
    "height": 1335,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JbACdACGWix/9JZdhwRAA/b3mYrqLK6wme30KIkcsgJfmuN1fKXC+R+WfEwQMcV/36tahf80xxYlkuHz8pXh/jTV0OQAA"
  },
  "apalle-3": {
    "width": 2000,
    "height": 1334,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JZAC7IFzCcwPOCZ6uuTWXz4AA/lVmy3AkOsx7q8Bf15ugeQkVZFBNvuew6uT4aIMdLB7xRY4TMmIVZeaG4g47GUd3rQAA"
  },
  "apalle-4": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBQCdASoUAB4APu1mpk2ppaMiMBgMATAdiWYAt9k7gRqLyNf5GbzUltItDEUeALhuoAD+8PtQL+38w4FYFBV7uQXYSLuDc3zTyJPOdZoFvyoatcuOcZYjGQ1fYtYT6Tnuy5QJWVrFg+jibhqQG+AS+9qUdHIgY8b+7fyYAjV+8AAA"
  },
  "apalle-5": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBQCdASoUAB4APu1mqk2ppaQiMAgBMB2JbAC06CIj2XFx6U623hlckMkKOPKyifIkgAD+6dFU03t93vbNjGCtfuPB6OcklT+VROGvyxTzigXxx5HfuQ3z/nCRC41MMem59RZj0GwfOIUE/OOD43/umRB41jDqANlM63jnAAA="
  },
  "artist-anastasiya-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUABsAPuVepk2pJSOiMAwBIByJZQDKAAVQX4MWtIJngKZ1KHgAAPbp5zdunywXlPgm6/b+Z7FcjdVkbZ2EH3FP43rql4ZH9DjV00gawDcqO0FGS1RqF7cwAAA="
  },
  "artist-anastasiya-2": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBACdASoUAB4APt1YpU2opSOiN/qoARAbiUAX5wPDQXOLhSVfwcLHjo0c3H0gAP71ca96hRyZUu/Ii1mOn52+ZpRfb02xW8+5qDgz9sSakhuaZWT9cRliiyjG1dIyLY6rB71WaFldo7VdQ50LnVE4gAdCAAAA"
  },
  "artist-anastasiya-3": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwBACdASoUAB4APuVgpE2pJaOmMAwBIByJQBadBDwKpJbuhsB+Br2YWwfww34AAP70HdiuQpao7162x5cPgdk70vnBXmyDFvqrMZgsWxSKf31qgAWMMFamnFvcrXApKLeUjtTpFbGTvK6IAAA="
  },
  "artist-anastasiya-4": {
    "width": 1440,
    "height": 1720,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoUABgAPu1mq06ppaQiKA1RMB2JYwC7ABELMiyKAjx0pIUMvIyeZAAA/uvp93o/71l1r19gUTNI8yI7ro4lO9M+cm8iRl9UjwN9fG8XIGJFyLqOIPRS1MIM26ri0mgA"
  },
  "artist-anastasiya-5": {
    "width": 1278,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQBACdASoUAB4APu1iqU2ppaQiMAgBMB2JYgC1IUAAzOHsyuiIsjv7e3QvixqZUAD+vY+i5U/+WGpNa/3GVvirniQa9v9z3GKrdl3IsCcYISsYhwMJgnT0QCNY+v5DuIYaiOLtKcqLTR04QAA="
  },
  "artist-anna-1": {
    "width": 1108,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQBQCdASoUACQAPu1erE2ppKSiMBqqqTAdiWUAzUgSBIgcRm4HvlPcJC0qO/4MD8yxaBgVUAD3Hxg3XL0Yn7xO2VHnXZHQVdEaEEUv2grmQcORP16bSVUkt/x5nPVohvTkHwGMIdAI2fKSurCf9Zc/M/ee4Lil8G2gJ2AoiSzQOghlAAA="
  },
  "artist-anna-2": {
    "width": 1113,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBgCdASoUACQAPu1oqlAppaOiqrgMATAdiUAYoWX42vI0zfEUvUHsPeagWH6X3C0ZlSZgQnocSt0pSvgA/u1b7H6/5C2KRzUo80MACV1Sui8/aka8ham//iwp8qAYuACo5l5BjdU6e3N2Qtry1qvsArTsRUNhGzUSffIOfFjylnMBYqAsTqrsEauvXY+5qnCvKImq1yn9jdjEFpQCuCdh5znLgkVcc9oAAA=="
  },
  "artist-anna-3": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBQCdASoUACQAPuleqE2pJSQiNVgIASAdCWUAygAWbX0Pyn3MYzosXDj0//VF0SdkyaUAAP7qcd47Y1jOUaGDCKeDnuzfun4ZuB28FQjI8G5taOrTsdvbE3JH1eZu8/Rv8MB0BS9RLwr/TWMYq9xbuPXYTE/ULAo6xJfbUcAAAA=="
  },
  "artist-anna-4": {
    "width": 1265,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwBACdASoUACAAPt1YpE2opSOiN/qoARAbiWcAAFu1E4YZhlPcGnCV+3c+nl+wAP7nJrf/Na2lPAvBu2NLmWi+D5UY4b8CDyXSGZbkn1+oy+XMbJSCoOKemllwNPTBiB406c3iIoQAAA=="
  },
  "artist-anna-5": {
    "width": 1318,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQBACdASoUAB4APu1ip02ppaOiMAgBMB2JZwDO9GghSApUsw0h0KXplAO9zoAA/sK4YcjIIYiZmBGDOBvCCJniAkYJ885k4eQ1Mv8SpWTR6Ss1Epp9aarREFl6dqOrtl77eEl/hREeJlYAAAA="
  },
  "artist-anna-6": {
    "width": 1320,
    "height": 1745,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBQCdASoUABoAPu1mqk2ppaQiMAgBMB2JZwDKtBjetCNiNK23hY5fl6HlFcTI6MstAAD+8ioaIHAVyJaOWaKYKqU9LFDm0G8jV8BBc0BYGXHkLKBZCQQXzevkn2QUKwPCEGqYrGHscEnORVa5BAAA"
  },
  "artist-anna-7": {
    "width": 1320,
    "height": 1724,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASoUABoAPu1mqk2ppaQiMAgBMB2JZwDO7B6u/cY2wt7af88YontCc7RlqW8YAP7uLnPhxApy3Ozz+7dw9dRvNOwzZ5zS2FfyZ8irgXk6dYMv6C/1uqEJ0md4kLo6hLZeTBtLVo0zHWlzLKLk08PcHAAA"
  },
  "artist-anna-8": {
    "width": 1080,
    "height": 1632,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBQCdASoUAB4APu1or1AppaSiqAqpMB2JZQC2+yGEmqzE5AX/LST22glMqg/PaagHwAD+3EnTD+7qgat25z0RsK5s/EFqwPukVnzrqKv3qiiEDxJKp0Le+8Zqys+V6TR+OzJMZWRtscRbqKAcUUBl1qC1izoAAAA="
  },
  "artist-arina-1": {
    "width": 854,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQBACdASoUAB4APuVepk2pJSOiN/VYASAciWMArhwNXPtzy6lKMswICWNSL0vhgAD+cN94+GEqjhAZY7esZZqw+PWeDPXp3hSCQ0AskvVtJhkiwW2DfESuBgvnUe66jvLCUwvIONA6V/72wmIAAA=="
  },
  "artist-arina-2": {
    "width": 854,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwBACdASoUAB4APt1eo02opaMiN/qoARAbiUAVgAOuuIz5eadY0/d86LtWAADZ4UIwW5i2KCShPAQha5ym6eZpSlP0XINix1ZYnEdTlEbAfxiRLfLblvtGnwWhQb0OKSkrW/2zp7OAAA=="
  },
  "artist-arina-3": {
    "width": 854,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwBQCdASoUAB4APtlcpE2oJaOiN/qoAQAbCUAXYAQ5Cbk4cKA37OiU8vPBHMpyEE8IgAD+boIVqksKBtW8oM7wMrhX8nDyurmEOC73TWb/EFuTIrGBVCnwAAA="
  },
  "artist-arina-4": {
    "width": 720,
    "height": 1280,
    "widths": [
      480
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBgCdASoUACQAPulooU2pJqKiMBqtUSAdCWUAuwAWbY1WZaaoneiy+4GIRH8tVJDKHih/HYxtL6CwAP7V0E1SZc4DH1hxVQqj7PyO8udg7t/8Z+OoekSvt7wRlsHWJm7yJ4NWaxmXIr5xrI2G14FiMZ9bul3cwDSVjrDmTxHdZuXZ5+H8fAd+0AA="
  },
  "artist-dzhuliya-1": {
    "width": 942,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwBACdASoUABsAPu1qrlAppiQiqAqpMB2JZwDBzDTv4SX4k0S6pWeJr+MRSF83WoAA/ucE1Rc7P7Q5M2KIayn5WQYGW83VQczu5rzeUcVJ5EKi7YoWv2CEVKZH5G0/DvD02pVGKFQBdAAA"
  },
  "artist-dzhuliya-2": {
    "width": 917,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQBACdASoUABwAPuleqE2pJSQiN/VYASAdCWcAALvrTSgPDKO6xO/E92IvJIAA/r7z+9bH9yyF6Wn90rGO0lZ/bBgHfWKmC+Jr5WZV1MIxxjDEAAA="
  },
  "artist-dzhuliya-3": {
    "width": 773,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBQCdASoUACEAPulgpU2pJaMiNVQMASAdCWcAzFg5X4lee2eo1jb8veM31RWFZ3gTIAD+7T/ZIVhdH222mpx1pqU0kR8mtIvpzUGrPbZss1kNH7N0KQB0kBPaMAoRPyGgFrXSQGQLHQAA"
  },
  "artist-dzhuliya-4": {
    "width": 747,
    "height": 1280,
    "widths": [
      480
    ],
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBQCdASoUACIAPu1orVCppaQiqqgBMB2JZQDB/7ABX0atg4rQJBsLBmm3NQOTHc7iMTEoAMunURbYsxVjEUw7fszRxnsFEbpUIoofg7iR0aqvfeZdqZfrs94OiLQL7EfVBqGPlOQOXFsDk0+8X4AJ90GA0vi91+/0VW6uohJEKIwDzyKap8W3X7jhXYa66J7/RoagADVPTZe7Np+gAA=="
  },
  "artist-egor-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQBACdASoUABsAPu1qr1CppiQiqAqpMB2JZwAALnVWbfw7eWBuaoTcw8ZUBU2NAAD+7oQiBfjzfot0l7TMYtc9BEj6XT0T4AAAAA=="
  },
  "artist-egor-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwBACdASoUABsAPu1mqU2ppaOsMAgBgB2JaQAAetGL2KxA/iMnZqMFdQAA/u/psp2xQkT3zY/TrwB4Je7aAAAA"
  },
  "artist-egor-3": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQBACdASoUABsAPu1qrVCppaQiqAqpMB2JaQAALmrp85r/nw36vhH3Ot4mBJzvYAD+U/RDNpvNEbf7wR+yd7pgtWEslMC8yMo4Yj29BJnKot9+m+tqjAWhULjW156kdwAAAA=="
  },
  "artist-egor-4": {
    "width": 986,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoUABoAPu1urVCppqQnKAqpMB2JZwAALnVZE3MMR4XgJ9WbQAD+8L/NY6bNeDE/38vqs7HH+/LLRGtj/H354cOxlzR3wmp4TM7Yiu9pgeaSseoQAAA="
  },
  "artist-nastya-aziya-1": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwBACdASoUAB4APu1ipk4ppSMiMBgMATAdiWkAxgQREevwTAfTss2zmUrvAAD+6OzMnYMIBBg4ocbfhdCqIsQLP0doj9kE/7iBbgX8mZDccAAA"
  },
  "artist-nastya-aziya-2": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAB4APu1oq08ppiOiMBgIATAdiWMAAI915/HrdiuVbpv2v3gA/u1b3r+/GgfYxUAZ9oWnIz3Sshf57pPYqu6i4UxENuC2wJX2gJ0CzlV5fbxbp03AAA=="
  },
  "artist-nastya-aziya-3": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASoUAB4APuVcpk2pJSOiMAwBIByJYgCsMt8CaCMPLZKwYI6yu7lDaiq+u72wAP7x4Kol0wiuAb7qZULx/J8UaCFKepgU91lYa27ryZ1ru0/Er7df55igmnianIo2c1jWSJBMMLF2zZp51v7mezWAgAAA"
  },
  "artist-nastya-aziya-4": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQBQCdASoUAB4APuVepk2pJSOiMAwBIByJZwDJECHEokzo4nWqvyjyrU7+/AcuM8dabYAA/p0FnHZTn9Epy4Hw3yEAW11Sn13W726vGgMaMZimxXZTtQAA"
  },
  "artist-natali-1": {
    "width": 1600,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBQCdASoUABkAPu1qsE+ppiUiKAqpMB2JQBWGYwA1EkRAFrDBn6ivV8JKa0JYbV2ZyUAA/tSEduvDUM1DGmAWg5Kz1dPATiRkEBXh7HtSjCHFjw9LFtmipgpSRI8dfZA1ElgZ3hymCeb9/o8ZVCWm/9VhSS3rWA55ZjLAAAA="
  },
  "artist-natali-2": {
    "width": 1600,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwBACdASoUABkAPt1apU2opSOiN/qoARAbiWMAxNhXb+NldEw5jQtBqS6MsbparAAA/vTXLFaC3k/BWnSt7NIDsUiqHnMt2kohWdIAQGUzDahvcBtENn8C+TjAAAAA"
  },
  "artist-natali-3": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBQCdASoUAB4APu1qqU8ppiOiMBgIATAdiWIAnTLtANg6nRkv3GZb+qI4AiL88Uj0wAD+05dRO31TVjbvEb7ZUV8TZ9fouifO/SX3Ug6BbODyWf+bnEpX3/L3R5BE9dXNHZesGl9FOPOAvLQeP7uPAmyDa6Yw/M7qTB7Q4OKMu/4QwXUz3nMrzJSB65xjfigAAA=="
  },
  "artist-natali-4": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwBACdASoUAB4APu1iq1AppSOisBgIATAdiWUAuwAQ1zjY33ZGm7LHdiXfTNO7JYAA/rcbD41B0Y8vsKuD42hn/bFBS+N0CH7ta9XIsCM+s0xihJVHD5GQefazLQjwAv4eMa6Myjs5kLIWYwAAAA=="
  },
  "artist-sofiya-1": {
    "width": 960,
    "height": 1276,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBQCdASoUABsAPuVepk2pJSOiN/VYASAciWUAvkhHf9ytIqZgcngDoHeTbC1twvYAAP7zMn2HbCVVvvaXiRtYZ/C3xmbUswRT6JPolrf2kJG+JmKw816xF1zE7d7SiCbXw/TDGy/4anH1vaGvrr/kB/AAAA=="
  },
  "artist-sofiya-2": {
    "width": 960,
    "height": 1265,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBQCdASoUABoAPtFYo02oJaMiN+gBABoJZQDGfDJp95OfpltIUkOmqXj3PYJrvNgAAP70KnNBZgJkDL5IIOIIcvYkwR4ZqpEv2ZLXAeh23+bb/8Nc4oAA"
  },
  "artist-sofiya-3": {
    "width": 853,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQBACdASoUAB4APu1kqU2ppaQiMAgBMB2JZwC7ACHfjJv7YmlKD2ew4z5CGOu7gAD+0tuE7DWKFYW+JYnlbVOVesoqms7jAQucbzVwsJnmzTEbSl5ZCg36S7AAAA=="
  },
  "artist-vlada-1": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQBACdASoUAB4APuFipU2opiOiN/VYARAcCWMAsOwQp8pUYGgWnkSGyrljpgAA/vQp4WAV8ispRbwIDpW//aQJoUJILfaI6F8NIHRyFaDBxqOSA/md9McpL+k9b4khRTAAAA=="
  },
  "artist-vlada-2": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwBACdASoUAB4APtlcpE2oJaOiN/qoAQAbCWcAyrQh4dYWEwjDnMuZxliIWzkAAP7ujzqtucXMHX269r/ySyRwK+Zvx2JLXhm5S08toDSg1JjLIN3YAA=="
  },
  "artist-vlada-3": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBgCdASoUACQAPu1urlCppqQiqqgBMB2JZwClrBZ3kq+ESW3QqxmzKHdCj/Gsm1uYOAldn518O68gAPad2kAVyV5LF2fLq8BgiWXkRTaeLCHkzIrO4qfwYvrp6gpMZUIFrr1V9gMU17m7u4jToCj0Kn+wVT4cJOUB+GPK1j5vPfEUoEwQAA=="
  },
  "artist-vlada-4": {
    "width": 1494,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQBACdASoUABsAPulep02pJSOiN/VYASAdCWkAyFwHhyPNgFBkLcJZwkYxpyb9AAD9FHgZtmw1f2zBAgjsk2YxDlJ6CLCL5aGjP3G89hfTHqtvQs3ZnpqSikDEUqAA"
  },
  "artist-vlada-5": {
    "width": 1080,
    "height": 1920,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQBQCdASoUACQAPt1apE2opSOiOrZoARAbiWcAyvARplUBKjpV+Ma3IXQM7rP9AazUZoAA9weUmuenaFe1UFhPHHMurDBcwzkfsRaghSZFViplZB6rzU/5PL2ZC+r7m8oU7UcMCAvDa1BbJDkAAA=="
  },
  "artist-yuliya-1": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBQCdASoUAB4APu1qqk8ppiOiMBgIATAdiWcAy+A0b8bY8zZcLmt3rAgO2XpDh9haiQgA/vDHnUdvm+zsB+AK54hNMQxf1Okq4yuCKjYUBdOIiAh/2y+unTA1YA44YjooAA=="
  },
  "artist-yuliya-2": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwBACdASoUAB4APt1cpU2opSOiN/qoARAbiWkAAFu1Fq/2K/+o66Y2V5JmPn+emFAA/vQi6546fUs65Mf+W7eN0+MZjhN/q+8cjBRVaaQhKex4GPSFG34QAAA="
  },
  "artist-yuliya-3": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBQCdASoUAB4APulcp02pJSOiN/VYASAdCWUAyAUgBh9l52W5bkYpeiqirL8mwJGplH5gAP736M23f9uOKxbCTf5AfeHnfpWvdgv/DbonHAUMD+jepAHu2A7JIe8u9J6V4wBi+XUP/X1GCrfizqym4ohnAKqeEPXa4AAA"
  },
  "artist-yuliya-4": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQBACdASoUAB4APu1kqU2ppaQiMAgBMB2JaQDNhCHfCRnlsFS5Vs/KIhGCWGgA/vQnxRqn3A3udN8Fww1PfWdXxgKDM/5dT63xmZAVAAA="
  },
  "artist-yuliya-5": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBQCdASoUAB4APu1krE6ppaSiKA1RMB2JYgCsM2QA6gGkbq9shzMSbcebCmLkR0xjAADtBYcHMYPvTMYTlsLs2h2+wNVuXgtm4vVh9vfGwXhrFAsOVairIgIdNYuiK5yGgS2cKJ4kbqFgx17peIGIOcJa2KhsJDHAAAAA"
  },
  "artist-yuliya-6": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBQCdASoUAB4APu1orlAppaQiqAqpMB2JQBYj6rgwCE+pL72/Shc3gsPgQAwXmu0JiwAA/uhQI26/QnGEb06heSiUfNQMLBxiDY9Rjgf9Se+dO8ABzcbqagDXl0cdf+6sqMQ9M7huYe+ZyqwOR5aUvjSda8NcdtbCS2AUd0IuRo2Ks9CofHG9viwEoAAA"
  },
  "atelier-1": {
    "width": 893,
    "height": 1300,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwBACdASoUAB0APu1ur1IppiQiqAgBMB2JQBYj4wAfOXRJ9Qs67aAu1mqL/AH2/gAA8cPj01/2HJuwNPkhupt4xSRtNImpPqp+nK7Krs7ufGpxSbCPXxwXnDizDEwlSgjhdW5C2zBvZRSeHPna+nwrQ+D30hQFJzgAAA=="
  },
  "aziya-10": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQBACdASoUAB4APu1gp06ppSMiMBgMATAdiWMAsR9CwVH3I+zf1qPKe4SKAUv+5gD+3NXyZYg5wbdQ/BiZ5g0qy+j3pF+tGafS0XWW+tG+pb49kDcoL5+RfmNTyem8CyKDDflQne4ZAZWpAAA="
  },
  "aziya-11": {
    "width": 1328,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBQCdASoUAB4APuFWpU2opCOiN/qoARAcCWwArDKDNtBJpneearbG0QXZqzT7B8TC5YjRUwAA/vKkn+41wV/7A0/a/mgCU4Q+OWkOak5D2r/wtvKqbzxVfKW5V9FIh5TF+k7t4gm1mB12eAxS9XuwgJWgWBx+aPgPqow28WS0lSeti6BGy3gj+MEXKqCeSxMuklEBLA2MuzQRcAA="
  },
  "aziya-13": {
    "width": 1500,
    "height": 1000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAA0APu1kqU2ppaOiMAgBMB2JYgCdAB6OOtu564XaQAD+zMwvd52oyBzlrTdmPbL8bFjeBDKJ+Xr752GrgFB5rDmgsY9kF+/xOyfS8AA="
  },
  "aziya-14": {
    "width": 1000,
    "height": 1500,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBQCdASoUAB4APu1orE8ppiQiMBgIATAdiWQAnTKEgpgRM3FYjAQO6avpimToFY5GwugA/rnfckvr8QOExAhgJROPcB6lb+lrzEH1UdoBZK6va1fLasILvB6C35lKfjBOKoXQ3vJIcphQqmIfxxo2zCiOR1X4NPsQjtCweNGM4HciWAWBQAAA"
  },
  "aziya-15": {
    "width": 1500,
    "height": 1000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZgCdMoADDWE54cM7YwAA/uXPAYUPy5fNQIspIfXhBuhzydhSlBku74s5qTwvIQ4MLoN5aLgAAA=="
  },
  "aziya-16": {
    "width": 1000,
    "height": 1500,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBQCdASoUAB4APu1iqU2ppaQiMBgMATAdiUAXZmq4NTEJGwnn3waaEj7m1phNljzQWAWQcAD+7BxaJOhq6Snz0qPKHu8VKx9WCbq5wr661x6qQQ8PKNCJGR/h+vJ+PQLWD6me6e1Bib0wuwbxZupSeLyenz8KEKRbGGBoTIAAAA=="
  },
  "aziya-17": {
    "width": 1000,
    "height": 1500,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwBACdASoUAB4APt1apE2opSOiN/qoARAbiWgAnTlBVgAgy3MXgDlycXLKZwyb2QAA/u9fHR4iqVApyLJgRiOQoQaRCFmwPkwJ6azhVIXInFFfqiJ6TBh787V9AORmRDcV0BxDtYyHArW62X8oXUUCQAA="
  },
  "aziya-18": {
    "width": 1500,
    "height": 1000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUAA0APu1iqk2ppaQiMAgBMB2JbACdMoRwACx/zTUW1SaTRagA/u7AEjJVOvLDA/RqvLUVsTlrsRbfT4h7BaLmAe3SuhtsIAA="
  },
  "aziya-19": {
    "width": 1000,
    "height": 1500,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQBQCdASoUAB4APu1cqU4ppKOiMBgMATAdiWYAnTMbLPwacO6uW6m6cuvojfAEpvH38+brJyfgAP7lz1+mUF7yOCws6UmI2rA4JTx9fz6Klch4ZZPoh4JRq/2dyPb69jPbA9JTiGxMu68BWn8uFNmcmoAvGB6cvfD2A/WvV7GHGl0uswXHBKObxHT4Cr4W8TzAAA=="
  },
  "aziya-20": {
    "width": 1000,
    "height": 1500,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBQCdASoUAB4APu1cqE2ppKOiN/VYATAdiWwAnTLVPOgS1vug2v2i3PTwrMmtuXsAAP7dnpCuZRqO+9j1ymY5XCApwhfVKMhNtBLMXdi1dfn8q6dFYSAYduPe5NpvoiHr3atSJFlzzzeg8BYGNhQWSr4xg2Oy/NP6UURYsYAAAA=="
  },
  "aziya-3": {
    "width": 1457,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBQCdASoUABsAPu1gqk2ppSQiMBgMATAdiWwAnSiAANO3XZ67Jum2wZI34Gw7pRZtyQD04AD6n9EmVPD4Rh+G738a4GqUA58/aw0vHu3d5aYY31a+wD/hls7bK+KlL0VRZ96mpC2/B5Ug5PUYN2/JSzmsD5TgNGhtUzycnOOq8IMp+IUXymcbQPv0dbNCUn/Xlm025ECJ6RWmWvwAAA=="
  },
  "aziya-4": {
    "width": 1411,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoUABwAPu1kq06ppaQiKA1RMB2JZACsM2QAmL9e9Vol0td1r4qGiUQAAP7drYI0Yt6ccoU2MuMQwpk1mrqviqkw3MCluL1W8+WkDfuxP+Ur+tBBkhdJp7FzgHup8nzzVNy+j2Y5ahERZ0USFeOXnwh9+iUO0kgL0AAAAA=="
  },
  "aziya-5": {
    "width": 1382,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoUAB0APu1kpk2ppaMmMBgMATAdiWwArC+gAPajswFXmULIVaqSsQ1bvFLYwKrgAP5w8WCMBi0Ef/ccTyRG3xtbihAxDbOsTNZL/+OZZSud0zQzXC1X8Me6qoZDQcH9rrKt1ZmgrZL3CfFyjJ1Y/oSPaANB89gKWXcAagbB3wJtiRgA"
  },
  "aziya-6": {
    "width": 1354,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACQBQCdASoUAB4APulep02pJSOiN/VYASAdCWwAtshFYAeygi7OF5hV35nRJcpusIgjLLVfIAD+93ie5X8lVQmDTXb28oFutS4dj39GpA/OamZ4TCWTJA8fKML8V10vwDdiNDc0RIypNpgkfdL7QFoUS0bZtFgPj8OznU9ll2/3TFo/2VsW6ZJyr08CT/RAk2Ju7c3tAAA="
  },
  "aziya-7": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBQCdASoUAB4APu1opU4ppiMiMBgMATAdiWwAsOw0cK5yTMPF9IbWDy3UxOL2tHa0KWAA/u7xpDdEgk1S1/MeptvgqL9U8jw3yMd88xQFSuQi5hrZPNzRGiy8YflEsgjbcPQTyNFVWBkM6nTpeNfsPVoCbXi0r6UfOgiHMtQYAA=="
  },
  "aziya-8": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQBQCdASoUAB4APu1kq06ppaQiKA1RMB2JZACxHy/BKJkkNvbswMe3C9/e6oxWyw0cAAAA+t3Lxa0pE3ic1+QJV6HW8AfCZJgbj1T9457N20XGJ0WuscCjdXGGtgeD3fcPNQsKEO7pgni9fzpZfgVNB74cL4JP/9wz3mXSwkE5SY/AAAA="
  },
  "aziya-9": {
    "width": 1334,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQBQCdASoUAB4APuFUpE2opCOiN/qoARAcCWwAnTKEf1ApQ8Ac/9R3XefJ5DWmi9bEmV09V41AAP7ulnCL7+/dyNK8kKTUUjFoX2fUxDssq4jAtp96prXlH4Q9XNZI+zYbT1I4FW7bROpDfjSPmAHJlLP4Sf/Y0o/m/tX19rk60VJx43SR4Cm/1WL4jGMXEu41hVdICKOAAA=="
  },
  "bal-anastasiya-1": {
    "width": 960,
    "height": 1672,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACQBACdASoUACMAPt1YpE2opSOiOrZoARAbiWUAxrgWYQ/RKn37gj9C9ElAt8AA/oJS3fs9TCwPHTtSGoTKhUrUDeMBfqP5bQKf7/occGCH3GjWcKfildXOOEPFhj9zcDXjAixbd0GoWjT7HFdXB+Cj5OdRxHh6PM3YeHR92D4ArqAO9W052z1FAAA="
  },
  "bal-anastasiya-2": {
    "width": 960,
    "height": 1623,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoUACIAPulep02pJSOiNVgIASAdCWUAzNAWbq04/qjHu7UCBcoAAP7xLlCk6J1S2dvd2sk18TsQ4T7mltx0bTnZJP49TO+aNww1l6WHDwOCiymlYPNBQAAA"
  },
  "balerina-shou-balet-1": {
    "width": 754,
    "height": 1300,
    "widths": [
      480
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBQCdASoUACIAPulYqU2pJKQiMBqtUSAdCWUAwNwWTiS9GX4JxP8vlvw2gy2br8fopTvXCMoyAAD+ujfyYbwWAEYNt/n1jZf3DOFCNwXBLsNcWfvYfNuESDg0zhbQxhl/C9vSje69739jLmQcE09Yj5V8Ih/N2VfVm4hCffTExiqJ/YciS88HNoFzvdx9xWmEh08AAAA="
  },
  "barokko-1": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZwAAWp5F0wC4XyzOXxwAAP7w1HF2hNaBR307UzZp4uvQo70hD+L97xF+NIcytfiKp696j6AAAA=="
  },
  "barokko-10": {
    "width": 1502,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBACdASoUABsAPu1ssFCppiSiqAqpMB2JQBOmUAAXtNKJaLmpJsAOkvlsRMqwAPqUC1dZgI/Wttrq5sHsAhOD+4mGoEEXQXROp1/Mx4QfrI64j3QgZmpVCpRmu5MjWvoLtDe85rLGH/vccTNofsBdkeBYBQAA"
  },
  "barokko-11": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBQCdASoUACQAPu1sq06ppqQiMBqoATAdiWMAuzNVwUwcJ+X45W1Y8YvtHlciDcL7wAD3ZvRgF3tS+Q9aJl9d928OiSazj5xhTnwhdRHXf2Kqv0qqTfEdgK+pE+S/+jMfncd1HF8sr1z4G32i0etuFqu2kDNa0ifnvTQB2AAAAA=="
  },
  "barokko-2": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAA0APu1kqk2ppaQiMAgBMB2JaQAAKnuD9AeqrQAA/uzekiiIvXt+ZnnOcu+Ja7LDn4B1I6T13gAA"
  },
  "barokko-3": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwBACdASoUAA0APu1kqk4ppaQiMAgBMB2JZgCdMoR3AB6RQ42VKoxld4wA/tyv/F++/3Gq7n1rAk7fk2k3vEmqCjqNaLQb5uCFQyPjG5EQAA=="
  },
  "barokko-4": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBQCdASoUABsAPu1mq04ppaQiMAgBMB2JYwDCgBq1N1G3S/BsyxLGJw769TJuPN7AAP6ptl16sF0RFcbCr+S5MWxOfNq9ZN30jtdywB3FipceVT2UZo75vti33wmVwJuw8igsQO6in4RskKHqaBgW9SaOm2XgAAA="
  },
  "barokko-5": {
    "width": 1586,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwBACdASoUABkAPu1qqlAppiOiqA1RMB2JZQC+SA7eRSXbq2MQM+Yqg6dSaS0AAP4uquexc1+1Me1Dn/cmZChvM8iG17hTVwjzkPEEmQ4xDfrYvr/fNF0JeVvb+67W6v04LE7RH6/ClRjmhsAAAA=="
  },
  "barokko-6": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBgCdASoUACQAPu1qr08ppiSiKqoBMB2JYwDBD46IgBwufk7drsiDcTx9G2hVElO1zO/fqsItoQMrklMcAP7alUxA9lyQIt/lR1g7w0+XdAbDcwOhT9bCnf28m9OKPKcpZG9A6EtTu0U9G/uRaEkBxkVagSCMUTRLLSLPfOvBuXrkIutfjdikXstFKk3LQdjkq2WvdyLugetBRcJSNpCKEYTD8+qnpSZcBXtxwAA="
  },
  "barokko-7": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBgCdASoUACQAPu1sqFCppiOiqrgMATAdiWUAyFwituHFOfk8GypuPGP2Kn/qeSTzOMPpeccpSlTZAAD+9CM6i+YtzAbZxhKHba+p7dv7h3h8kcJlzpmpwxCI2RzcjGSX9PvHJYN+Tw0xt26yeNSoc3XJgqQFAneyilNeaNky34txocRbhnWc7PxKA7Vdqzhq59gA"
  },
  "barokko-8": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBgCdASoUACQAPt1YpE2opSOiOrZoARAbiWUAzUgUPutQPH6d2r7AGtswuy304eWcuHKAmnBtAV5sDaIqAAD+8yW1FyLNlXPJGXOQg8dqeNAkNvCBBaHRHXUv03jbsWVp65N9Sl1OhrSQsPlt5EHyz9Lt4rJACbeW8nyHfPlQPjiG0t4i8GqFq5TEaT3VKjCQP8ayAAA="
  },
  "barokko-9": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACQBQCdASoUACQAPu1mq06ppaQiKqwBMB2JYwDBkBYMvVkkvP7CpsIvgx9bA0ldB9RrKewHYAD+8NI3/kCT7NePP8dDUly4kV78IN7p9Cm2AJp1ix1wt5FEqaYpWioro1h7ID8w5CkAZLi+nGGKsU7JBVva69Yo/ZOUIvLK8YEL/qy+wwBRpMrfbIhNUSQkAAA="
  },
  "bogini-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUABsAPuFeqU2opSQiMAwBEBwJQBXDgaTfQp/zymg+M+oUBgAA+daM0E1uPMrd3MIyEQJItl6zZwQv0XYtsO+GoKqtyMnEQUq4k6AoUsq8/1QopKbpAAj5qh2s68I51gOAAA=="
  },
  "bogini-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQBACdASoUABsAPuFeqU2opSQiMAwBEBwJZACdM2c6ADGP8cHYNyySbyrgi1/sgABgjLvp8byc7YP/2AYZjiVvbRjzpP5ClhW1QRm5PAhv18zjiAZCc5Wam6Fl00sW4l/BJnSYuYgAAA=="
  },
  "bogini-3": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQBACdASoUABsAPu1srVCppiQiqAqpMB2JQBYj4jXSgalkd8EOS42Dz/PgF/4ZAABy6JfVXoNPuoxcBVNNNCdAQ85VSrzMvJlQFNZPrvErnsyss98aF/gTP++HLgOZV3D2BoUnTPCcBvkikFs1gqV0DjcSSZYxKyGZWTn8ogWW4tAA"
  },
  "bogini-4": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQBACdASoUABsAPu1gqU6ppSOiMBgMATAdiUAToAFDmqaIyEhxTSN4hih/cCAA5xwloH2PN+YQuY7MynPyacfnhAwMwFEFuT7Uf2xmw5zpicJjVUhvk1gC6zvLhM4AAAA="
  },
  "bogini-5": {
    "width": 703,
    "height": 1086,
    "widths": [
      480
    ],
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBQCdASoUAB8APu1kp02ppaOiMBgMATAdiWQAnTKDyeQMUoR++9MlqxCpxrkHRYEWe96GSoAA/CqU74Jha/JYR3eO1MVH/e0peSx0ro3z0z3cKY/Um38DmHPGlDLk8oVnIz/9QH8n+osjEv8wjKcXBmwu2pFb9Izdwi/BJKmOYtSs6IqnYw+jGrde3+9j5K6EKX2OfL8tQMrgAAA="
  },
  "dikie-zemli-1": {
    "width": 1280,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQBQCdASoUAB4APu1kqk2ppaQiMAgBMB2JYwCdMzxnrEmjDaMJXgUQXmnnBITFgO6oiYQAAAD+9CtbRYYpIs7FK1GHroc9sSxBA6oskr+/zR58pCmLSFMskEPL5Ii6mJ47XxoZX5rlFrSQuJhgs2OUeQ5pRypEvgqoAAAA"
  },
  "dikie-zemli-2": {
    "width": 1280,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQBACdASoUAB4APuVcpk2pJSOiMAwBIByJZQAAW+teJEKV/cQSG9funoMAAP71bhHlucEkXUNmTCsnjs4FZ36rxKHbaVosAAA="
  },
  "dikie-zemli-3": {
    "width": 1278,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoUAB4APulgpE2pJaMiMAwBIB0JZWVuWUETN3sK94gQAAD+8KMPA8LcARZVl89YN2cNMGec/gPxlLuV8Wa91TqmxNvDuSxUhrFsOuHu1HRPFrrZUN4AAA=="
  },
  "dikie-zemli-4": {
    "width": 1278,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUAB4APu1iqE2ppaOiMAgBMB2JZQAAW+i4UPk/O7niPPyrRwAA/vQqb4LNpQWIHb4Bqtd0QuIZU6zHQZrxrhWhHA9fMxKAAAA="
  },
  "dikie-zemli-5": {
    "width": 1278,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwBACdASoUAB4APu1mqk2ppaQiMAgBMB2JYwCdMtDDTtPHl0coQthdjnCLMSXTWYAA/vQouFXvXG3t0xpfl033HZJOT5LlqTaYwxVLkqkNV1viVQOk+M1/r2S29jpyWbcfOIW7hA5v0iFahwpd7eq9766Ms8syzNgAAA=="
  },
  "disko-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQBACdASoUABsAPuVep02pJSOiN/VYASAciWcAAClVzcxDBZXHaUHYAAD+8rSyYW3siPOHnRmKJDJU8Duu4dHZQoPDv9ZwAAA="
  },
  "disko-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAgCdASoUABsAPu1sqlEppaiiqAqpMB2JaQAAPlQ2AAD+8G8b4CD2rudQ9szcfMYQUsH3umgHkZJAmsfgAA=="
  },
  "feniks-1": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBQCdASoUABsAPu1irVAppSQisBgIATAdiUATpmMALvf5+H/vct9zp/bS9FrnnJPrc0AA/q0USoSzucgTjn2e4dG66wGZ0tV8Q9XLRaG+oS31jMsjiCmaczO0oC2KJXWFUWpt4PzRAuF8SVmTSqYs44n+gr9jbcez95J6mbQcV7oFt0zWRZgAAAA="
  },
  "feniks-2": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBACdASoUABsAPulmqk2pJiQiMBgMASAdCWNfalSzCws/MAgrdcjX932QAP7wdFthZ+7ePyNrErYGZJelqhwudS93Ygsaqi508aB9kDr6QRZpm3/DJ+LUoIsa4OKCk9Mv8Te/8gObS/owPK/hImS/LcMgXaAA"
  },
  "fil-gud-1": {
    "width": 2000,
    "height": 1125,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JZACw7CHfzhdlkZ6wFCoAAP7l52IS1P036Zn32KjdJ+uiY72hfgAfBasq2H4IcAA="
  },
  "gaga-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQBACdASoUABsAPu1sqk6ppqOiMBgIATAdiWMAx+Q0b9C2J4Z5f2PjFzb/7MzsAAD+9oOmiGEYIRkgDu8IpKVbsrWBt6zWsURP6G3wpxIH5wxxIf9mykghlWQm4yAA"
  },
  "gaga-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoUABsAPtVapE2oJaOiN+gBABqJQAARHMojB2GTXRefLFjFyFAAAP72hFy9Ld33nSC/1kRdUVa87A2iWwaviuhXBfIB2jpBgUaRMJV5QUPLsQwTmjnmuAAA"
  },
  "gaga-3": {
    "width": 1426,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBQCdASoUABwAPuVaqk2pJSQiN/qoASAciWIAyNRXbE6l211vtOgMaNlGpqOeycQAAP75D32CVWxNIn0+TlizncbKxFfVsXp4eQ4z2Ld+ceib2yYbeJdYLkp1CpFxOG5uyQ/7DjfAAA=="
  },
  "getsbi-1": {
    "width": 2000,
    "height": 1125,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAwCdASoUAAsAPu1kq04ppaQiMAgBMB2JZQC7AB6V2INct2xNgAD+9DLcD+FXBBpx/GjRVBzoDguBqppAAA=="
  },
  "gladiatory-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAwCdASoUABsAPu1iqU2ppaOiMAgBMB2JZQAAW+uXS2c3qiv+XAAA/vQbEMChfCzf0GvF42DUWAAA"
  },
  "gladiatory-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBQCdASoUABsAPt1apE2opSOiN/qoARAbiUAXZmQwaFWKGjyqg/9BYxhstpVRSNoV5AD+9WlIcm1Tt7O7+0cPuc4l/PkutPdVZztbo9SgYeEd+zZDds6Tuay6PPqf9J72d6OMd9I36y0AAAA="
  },
  "gladiatory-3": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABwBACdASoUABsAPu1kqU2ppaQiMAgBMB2JYwC7ACHfzhlgHBEP216okeViiAD+9Btcljj1bOx1sSi/1n4gk06RYd65aPUF25N94yCpFVGezFYgRgPto5biCvQAAA=="
  },
  "gladiatory-4": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBQCdASoUABsAPuVip02pJaOiMAwBIByJQBajXRBp1N+QxM4kOMWfUAqbWE9HaPqDnAAA/vVpCBAYX7YuiJ0bXk/p+2XLy7hR75+IxU1hhgec+itqNXwJF+NzU0Uq850iYHWctmYAZAAA"
  },
  "gretsiya-1": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAA0APu1qrU8ppiQiMAgBMB2JQBdgAxkZhkNMwH9jUAD+8N74D52rTIZ9UHmQMQ+ITzS9H2zcGWcupFnkeZnRHAVCMZD8N9qtZeYfyXYAAA=="
  },
  "gretsiya-10": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBQCdASoUACQAPuViqE2pJaQiNVgIASAciWcAv+wX072QJW2O1S1er2EwdK6W/7vpgVgAAP7vI+qvZPBhblzR1wzgcxxYKq2EBkXo/ki7JfRSHsuawfjbmn/PCEbuYcyUxLjePC7HW2jlvd2IaFpC15KQAA=="
  },
  "gretsiya-11": {
    "width": 2000,
    "height": 1125,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPu1mq04ppaQiMAgBMB2JZQAAUnZWSjiRqFL3QAAAzZpdemyB4KxlM22OvVFAVH6RYK4+XvyDntcpjJGXJwWwxXB1UdzOfnwuvRAAAA=="
  },
  "gretsiya-12": {
    "width": 1077,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQBQCdASoUACUAPu1grE8ppSQiMBVaqTAdiWcAzuwoeB+mlBqHHzAeg/lJxyxhyVjLemYK1swAAP5UajdH1LNHSiZe90pYubhMl4HVCGa/otAemvU1rkdvaA8jNBq0jEIqGTL60Dfdnot7A2mHKefToSgiScQUoYegXlTL/xPXq1ZwwjMECrt8YfLGkAAA"
  },
  "gretsiya-2": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JaQAAMGtMJShFmAAA/s3zMpTHNBClgFHQf5pXq2yatYKsU0ZMRsjdIF2XDpuOcd4+HqYxdqA4pqSGAAA="
  },
  "gretsiya-3": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoUAA0APu1mqk4ppaOiMAgBMB2JaQAAWy/QVulj11sAAP7y99SWWDrakUrtMTpu1dEbEwmbSUd8qBs90RYv+ey14GDUifQyNkMGN2haHutwAA=="
  },
  "gretsiya-4": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBQCdASoUAB4APu1mqk2ppaQiMAgBMB2JYwC7ABjemo1P7HA8x6JicD+L654uHmL/TXTK9wAA/ufVUtRvJowi6pthfKQDaoGwzuoOh0D5e2iL/qgGy5Ia0RILJtrvtCTczoah1mzklT7hSK4mrfUKfC1E0QSZDd6ig01Bz30AAA=="
  },
  "gretsiya-5": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQBACdASoUABsAPu1uslCppqUiqAqpMB2JYwCsAAvmSu6AKauXGmzNAGNXlg+uQAD9/Y8yYBkdHg9UVGXGKwrH0dEJI4zX5uWBZwVDAyMkK8U5U4Lm6ymsaWb5wt4YsxIbQ4mb0aAoDyT2nPZKxwAA"
  },
  "gretsiya-6": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBQCdASoUABsAPuFcp02opSOiMAwBEBwJZQC3uBnE/lMsa+k+uVvEBl6qMSGAHmE4AAD+ym6CNj2pMlj1srQrb5BqdSdyPL+URTBfGpnOgWnttCgsQWMAZoKtQPzEm27i3zp9OG+KQm5CbkvUr9ex0gGgAA=="
  },
  "gretsiya-7": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwBACdASoUABsAPu1srlIppaQiqAgBMB2JYwC/7D56kkcTPjto9ErtNBovSp4gAPujfQWRs6/1WOvil+8rBTxIDtoUz5qERurygrovn85/tAArdamthsnXDXsa1NSTe4g5inSinJW0nudVju2b0q49fJsAAA=="
  },
  "gretsiya-8": {
    "width": 2000,
    "height": 1125,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAAsAPu1kqk4ppaQiMAgBMB2JZwAAW4TjJG+3Y55sIAD+8qPgF8Qd2V6ScIhXTZG9e+lpUWQgCgAA"
  },
  "gretsiya-9": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwBACdASoUACQAPu1iq02ppaQiMBqqqTAdiWUAxNgUFDvTQEQAvBR7LDByzNIQAP46ok7uBTEtFApami+s1VN+MiugsVVu2yRN3Uz3WgvW6KiQuk4CpH2YeVZP/pbC01LtTS7TDG8LfnQjNMg2liicb3p/hw95V5NeuiGDumiuJetv5N2AAA=="
  },
  "ironiya-sudby-1": {
    "width": 788,
    "height": 1400,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwBACdASoUACQAPt1epU2opaOiNUgBEBuJZQDIICzayOz9bS5cEapp/7OulywQAP70Gho+T9NXXbBHDmcEeOaRSACoZtFm6JXWcyDQyEktfefkMFj4oai+3d6AAA=="
  },
  "iskusstvo-1": {
    "width": 1024,
    "height": 1280,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBQCdASoUABkAPu1qq1CppaOiqAqpMB2JZwAALnX3QL3KvtdtEq4ZM7n82wzvjUWEAP7yqCZnG1l/Ncguos40Gdk8mGYT9mbIbhG41NCg9hNF0cn1G3P8s7JAj2o4qoYOAAAA"
  },
  "kabare-1": {
    "width": 788,
    "height": 1400,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBQCdASoUACQAPt1coE2opSMiNVv8ARAbiUAY5gQr4LXS7baVJOPeKmOdBU/BDy7hewoAAP71dRP4gHN7qTAR3axH++pcmEM9fCe7z+Au5MmKsD7mDy14JqOsl4kllQkAxnom9BL29WfC1ODxe+0Cr+iZtrgn5AAAAA=="
  },
  "kombinatsiya-1": {
    "width": 2000,
    "height": 949,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoUAAkAPu1krU2ppaSiMAgBMB2JYgCsACB/oKcUmXMrfQAA/uv89amIXSa+7mlMu05VFPretRpBQRF/6XjVv67S+notZoTE/4+jsBIKgAA="
  },
  "kombinatsiya-2": {
    "width": 1080,
    "height": 1920,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQBQCdASoUACQAPu1iqU2ppaQiMBVdUTAdiWIAnTKABEWqu1x+fU/7HgdR4UFfsFkvj58Cg5AAAPnn08V5LfUu+38WRGzfXEiWrQaEH8sfrRtM8RFPmmaAmreSeHuy6fPJ4roGRY+8lqu8IJ4JEcRFf5siKLMp0FkEGyWDfoqcvP4WQ6lqmzIo/+NoiIqpAAA="
  },
  "kombinatsiya-3": {
    "width": 1080,
    "height": 1920,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwBQCdASoUACQAPu1irFCppSQiqrgMATAdiWQAnTLCQGgrtt071qlyqyxNVoNFNGcqAvHIIjr8AAD+6OUN6JIwtYgq3ikMfnoikp166+SDn/5mXBrHsazHfilf4pTge9P2u3vI0n8o/uJMPsjIg/NsBnhNDK7v1kGM/W8vn4Ph+egZrDWEurbF1dle/Bl755DEN1VeX94QqOnYS4AAAA=="
  },
  "kombinatsiya-4": {
    "width": 1080,
    "height": 1920,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBQCdASoUACQAPu1eqk2ppKQiMBqqqTAdiWQAuzNVwexB3UT4yd386bIkrGKp/q9ESAAA2zy5OPsvBXOKkcILFetnHoklPS/ea667404zTrykPD875SuKsXHUKDqbK9e6gFVBCGglH0MH83lJz041DnNSldrj/whKHP1CCWudfbOClkEl/qJO7cWLA6tgeM89RiAXZtBcFDPD47FnQAAA"
  },
  "kombinatsiya-5": {
    "width": 1080,
    "height": 1747,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwBACdASoUACAAPt1YpE2opSOiN/qoARAbiWIAnTLKcYAWRViBR92zgMPOu6H8uIAA7QI9jXt4c/A6u+8wY/4MKHFpDH6ez+Ecz9Zha1S2XYgxA4PtMR7VTFAFhO/HUgyA5OuitNUgkoVRT1EpsFs3eJkFtm4AAAA="
  },
  "kombinatsiya-6": {
    "width": 1080,
    "height": 1732,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwBACdASoUACAAPu1or1AppaQiqAqpMB2JZgCdL1AAb7xhekmdzjqXev0tNdcAAP6wq2ZnX1Esfb0NieaESTMhG4NgyhqKSQIwdIkaoDfiiZoqBkyfnigE8WnU2bjZ/PGM6d5ttBvA6YN3CtWlaKqbRcl09d9J+GJKcKYorFHfaI61WHhCSQlwAAA="
  },
  "kombinatsiya-7": {
    "width": 1080,
    "height": 1670,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBQCdASoUAB8APt1YpU2opSOiN/qoARAbiWIAnTMTAUgkj99x7wBxYQ5iwwp8Qy6HXlqKAAD+405DC0871yrqwsmkmsZW758OZ+Db9+XlnxguF8XjmyGhFaZ+1FpBuM64UNnUbmubaYdunHIVmBUciojMQnKM0Cmqy/DIAAA="
  },
  "kombinatsiya-8": {
    "width": 1080,
    "height": 1637,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQBACdASoUAB4APuFgqE2opaQiMAwBEBwJQBOgApquvHyCkVWT9H1tWITLM6M3gAD51qsm01usFR0k/IqswGM+9tJdC1xKvUQMjJklHEDeOQtSCFBLJbxtwGReKabXpqeQ5cXboMQnw2aGuTrb1wNdAAA="
  },
  "kombinatsiya-9": {
    "width": 1080,
    "height": 1623,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBQCdASoUAB4APt1apU2opSOiN/qoARAbiWIAsSVBPNAJrAO8oYtVVEuFRd3uyTL8d2MRc34AAPnXwJj5wR4C7sB5Z6ULqWno5/jSjPP+hez3wPxSBBX1/gKywLaK54scK023pdn1s2YheobFMGHzWDMC7GmTwsdSuEfgAAA="
  },
  "matritsa-1": {
    "width": 2000,
    "height": 1331,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQAASgHmbHI5AADODbQ5zehUUy5d2cJE6JvSG9yeZ5CBlD0LrrNGjVAAAA=="
  },
  "matritsa-2": {
    "width": 2000,
    "height": 1330,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAA0APu1yrU+pp6QiMAgBMB2JZwAAUp8lYSDy+3hhPAD+7qGNg5VYeN/xJmQLKmHWao0GfcVnyfAA"
  },
  "matritsa-3": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAgCdASoUABsAPu1oq02ppiQiMAgBMB2JaQAAe2NAAAD+8LUw1Gl5+dCBdLGP8EeIRrGObOHAAA=="
  },
  "matritsa-4": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABwAwCdASoUABsAPu1iq0+ppSOiMBgIATAdiUAXYALRKZ2QZSgA/vBb42iFBkwrzVFT3wvmXMHJrsv+MVvopcWvmtbF+ZKyoBRtxogA"
  },
  "matritsa-5": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUABsAPu1mrFAtJSQisBgIAaAdiWcAyrQWxNd3sAQAAP7wjHyRpLA9194aRYbAq3EVMNb4pgA="
  },
  "matritsa-6": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwBACdASoUABsAPu1gqE6ppSOiMBgMATAdiWdotgAUpBEH9iNVAw8oNQAA/vQdV9OxFa3ocxF+69r3SSNqSmeJoNScCd9PJsoAAA=="
  },
  "matritsa-7": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwBACdASoUACQAPu1iqE4ppaOiNVQIATAdiWcA0fhIGZ5xB0VWrjP6uPvFJYqAAP7w7mt+BVnWnx2nBqDyTcOOKiZaFsFXQQOTFI5NzBulV4C+poAstOaeCWGQydNqqC3yHlhGABt9kvUM9/JXAAAA"
  },
  "matritsa-8": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBQCdASoUACQAPt1Wpk2opKOiNVv8ARAbiWcAzyghXtI3th6mFIUBDb1FA6ttZGvKAYMOAAD+8p0GDmQKOGoFR4sc9IjdVnPI1hBmzjQMkacRS2Y31t2ZGZUnoMm4NjlEb2KGNIrFadwUBMfqxB5Sw1PEMMOtCeBIKswQZeAAAA=="
  },
  "matritsa-9": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBQCdASoUACQAPulkqE2pJiQiKq35IB0JZwDC+BZf6VDWC+4bosGzEgQ9ZgL+7shsgGmxr7AA/jM2R5UR4LaWPiIHHwcBfXj5I0Nxdq9H10Z624LtHdNPWnzwqO/MwziiAU+zuOxaeJhwhEDXuhKdnQ9LP9HjMIMAAA=="
  },
  "maykl-dzhekson-1": {
    "width": 1440,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwBACdASoUABsAPu1kqU2ppaQiMBgMATAdiUAQAAByTqJ+ZKqLAJ5YXHEruAD+70wa5SkpIeYsu7Nxg37jbJzOFmm+yRQ2zsTGZojhiZajvwoZBP4fpuU6pzLg4uZQCfqnhrRBsAA="
  },
  "maykl-dzhekson-2": {
    "width": 1190,
    "height": 1322,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBQCdASoUABYAPu1kpk4ppaMiMBgMATAdiUAWo1BntwQk7CDspAu3IUuhvh+Napka1AAA/unbZYoMfz4S1iO3E9MIR0MpBgf29vxJiCd3dRRQLTUFD+SCuAbrFHazkDEmNp8AyKMz6mdgpo3iD4ILZkvPAAAA"
  },
  "maykl-dzhekson-3": {
    "width": 1024,
    "height": 1536,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQBACdASoUAB4APu1mpU4ppaMiMBgMATAdiWIAxNg0b+eWN/a0h1IHxfWEYhfcAAD+9oKEjQFwV3Ni89zwieOXI0LTta5Iva0LP0tVbwu+veyQkp69CrPgGSuCbPzQ+H6vG+6koNOAAA=="
  },
  "maykl-dzhekson-4": {
    "width": 1024,
    "height": 1536,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQBACdASoUAB4APu1qrVCppaQiqAqpMB2JZQDKABEcxHBesUh+TMQfw7EAAP70GqEmi6Qdw+InTB9JrNeX6Z021o3VpsWsRlFslIkbYAxAdZRKgAA="
  },
  "maykl-dzhekson-5": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBQCdASoUABsAPulgpE2pJaMiMAwBIB0JYgCdMxs3WEJLiodzotJSlYV1a4WptxwAAP7qIzrAMwRsVWIrUZSD+dMLFkZr9fSxNpyO7649E+qyshk/wBZ/rwa1XfaLiHi6FWXBI789Nt5epOTZXPtyxfKOQuixzzxiAAAA"
  },
  "maykl-dzhekson-6": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQBACdASoUABsAPu1gq1AppSOisBgIATAdiUAWnQGCgPeOBB22fxS6uvpgAP7vTDACXAK7ilPDs/PHPuoWoM2PlguslWwQx953ByOIHyRCbdUT+Ch4HyHfrJoCCfvQ4+wT3fgAAAA="
  },
  "maykl-dzhekson-7": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADQBQCdASoUABsAPu1sqFCppiOiqA1RMB2JbACdMoR42QiA230G7G8/ZJPyA5oIt7alm9NxotyAAP70vqcXayxkUxOeEsrNuYYPTplcy0un6NHCWqqEYxUsS4EKc4+X3vQcLDcCl3B1S8QdZL5VeKI0os/vyxdZ7rNuncu2yHVRa1NnNfsHSZBW4x06tv0fBufAJQJd8VfxqJuWqo/48TP+snP/BedAD+QAAA=="
  },
  "nimfy-1": {
    "width": 941,
    "height": 1672,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACQBQCdASoUACQAPuVeqk2pJSQjNVQMASAciWMAxgQLNnAVR+ub5Z3be4O5abXg5tYexI5noAD+8X9Ilb7NZwZswjCsiXtFTouG+x83v5hIj7UU1XUMOrt4xCedVV2KR0/WVEEAXLRlmlcw6HsiU354Z5fPDGA9eL6BtecnGEsogAAA"
  },
  "novyy-god-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBQCdASoUABsAPu1ysVKppqSiqAgBMB2JYgC7M2QBqgBu/lp2rK4ZeI4H9mC955RAAP7rzmixBMjznlxO+dgg7ET0yb7y+pTV/6HslZ+xEfcyPFrwKtzA943XcPgfKHrDcfCWo9bZz9ldcYblJlUq8/geQZ/nq3+1YWmmnKS+eQAA"
  },
  "novyy-god-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQBQCdASoUABsAPu1gqU2ppaQiMBgMATAdiWQAnTM0P4C0QLvwN8qMM5VEl+AuIVyHzz4rg6AAAP7un0hUbJzmimkx1HC9G4+SwxEuNf0bw4XrgtDpXPLvknMSWeYE+PX42FK7/F0yvw7jWYW2YoOu/d/gKT5qIFJeBDWn1MSwG0S1IjE1ccLypnGNk9RnfgOLn1OAAAA="
  },
  "novyy-god-3": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBACdASoUABsAPu1wr1KppiQiqAgBMB2JQBWAAiMIAbkYI5HdNBDtJ3AAAP7ufwH7xwa4JF2jXGgwC1t4oHrrUU2+cLyFY83XoKRzQOrmffCtrdyuqlXSV3/yVd/sIQGiTwAA"
  },
  "novyy-god-4": {
    "width": 2000,
    "height": 1333,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAA0APu1mq04ppaQiMAgBMB2JbACdMoRwACUNB+QzdlrMJ8AA/r54D/iVaIGcIx+Fq7/ENhXaCJ+XQEsDbucBBZJzn8QHtjSZ7MQLnaBJI6w5HJgAAA=="
  },
  "novyy-god-5": {
    "width": 2000,
    "height": 1333,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JbACdMoADS/W2w4FglSYAAP7vYyaBJ5DMHnCGeoXEVemwdBr9gya8CfIbL32ojBAH5pDDdvgAAA=="
  },
  "novyy-god-6": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBQCdASoUAB4APu1cq02ppKQiMBgMATAdiWwAnTKEgNgS5elybYRYMXIPs6Npx7FhCAAA/vQy2Bv1Fk6T6BBCoIGokm0UUTkgqtL4AbCe8sNr1asbKfBNb4/wsWjJhLjl3ObYVVieOi12VGvGaIquKhQmBLJ/pUa6BqmrTMd436ypyHa2STXHGZICFCKdohAAAA=="
  },
  "novyy-god-7": {
    "width": 2000,
    "height": 1333,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JYgCdMoADTqcFW16ARJmwAAD+7tivQzuR//Qk54MvfzJrI1m9avjrld9pkKL7MYpW+0yjyXk6OcAAAAA="
  },
  "novyy-god-8": {
    "width": 2000,
    "height": 1333,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JQBdgA3ZdwZrET5iEAAD+8Nr8d7RV19jICnn8DYd3DTEjeSi/TgHMUEbEiWtb2ii1BjPqVt+lpsAA"
  },
  "ofishl-1": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoUAB4APu1iqE2ppSOiMAgBMB2JZwDDrCHft10Rikwx0Z4MAAD+9CLqZRMjJBh6uQ5HwOjfvEGSh6b60oiEdcW0o8msXUAA"
  },
  "ofishl-2": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwBACdASoUAB4APtVao02oJaMiN+gBABqJZQDI1DJMpVot8QmhOce8jZKgQAD+7G3kZy7QUbXExsSckcR7XY+aa3/jGt5cduxly8luqQXqT+MJ+HLlocj8d2FfZcOpCJwAAA=="
  },
  "otel-1": {
    "width": 1283,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQBQCdASoUAB4APu1oq08ppiOiMBgIATAdiWYAv1k7hKyOtOb8H6QXgHEEklN5ZVsUWhCV1gD+5nYumutbUpdvze5O/W2WPjiC7WDftzeYva1q5nDZtTfjFPTZDzo1SGqqV51HX7iRgnFy0zcd1GaegbABxMfsTezMQi3+jRecyQ2pkAA="
  },
  "otel-2": {
    "width": 1283,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBQCdASoUAB4APu1kqk+ppSOiMBgIATAdiWQAnQA0cDE6ohaS+dJVbY6ZMdJnjHxQAP70UfU/L4VdFMkpSqj4imG65Zk7e5K7caDE1JIviByR3A8ei2vhlvF27tle2oO1kWQVrHaju020ctSYEzpzSVBAV6rymZIHKmbaQJtFCqvuAzcbIgUBFNlUf+gZht6C/NOrtUhb9OspAAA="
  },
  "otel-3": {
    "width": 1282,
    "height": 1919,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQBACdASoUAB4APuFUpU2opCOiN/qoARAcCWgAnTKAAz+m7/g2xVtRnk29z8AA/vQqdD3PQ0v1B5E6tZvRqmL7PSiTvfD2Wsb/ZYnLa9JeMd+dq4qAMMf6k/2LSxzMWrwu8Sh5Rc0N+lA4FWq5TreUrjas0lIGWa4g0aZnYMMBcduiqSbIwAAA"
  },
  "otel-4": {
    "width": 1282,
    "height": 1919,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQBACdASoUAB4APu1oq04ppiQiMAgBMB2JaQAAUhMMUXw1Ctbl8GJYjk/1aU3JQAD826ZrRdHVvMLlr2ZKCyZUMS4MDycn9mISoEGvx6fNrj1FSbQ2ryl4X9cSHlmf414jzkaKmLhQ+dy/zA4ZR19QYAAAAA=="
  },
  "otel-5": {
    "width": 1025,
    "height": 1534,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwBACdASoUAB4APu1gqE2ppaOiMAgBMB2JagCw7B5wZlIm2djHdZS3tbYleI1AAP6HAytvxmnoCds5BZHNcLkj7YEdWRXIuJGuN+ki4H4XevVMY3GWKYodQ0pNH57Ak8u86YJ9o224jtH/cyMInuZbrYjlgFO/gttGKAAA"
  },
  "pakahontas-1": {
    "width": 788,
    "height": 1232,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoUAB8APuFUpE2opCOiN/qoARAcCWgAgPcHyAVU3Awkjyz2zoq/69xFAAD+PAGf1GuZg9gWEqVe5DyR+hP+wf/zBKes8SaLghsOJsXZdzINL+mATN0bZ6KotdTp+QfGL2GdulXz6+tawVfIKcj/fWDkyzphl1MAAAA="
  },
  "pozhary-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUABsAPu1qrVCppaQiqAqpMB2JZwDKtBgG31k+Xfa10AD+8Dy9i4qyHlV58bI2Z/OWT45d1jLMlgAA"
  },
  "pozhary-2": {
    "width": 2000,
    "height": 1500,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoUAA8APu1iqU2ppaQiMAgBMB2JagCdACIG76zK8L5/Xu+ssAAA/qdUP0U/wpVKUGqQ0OkFz5HYCT5oMEWw7Mfd3dnrFk49hjZOO9gAAAA="
  },
  "pozhary-3": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBQCdASoUAB4APuVgpk2pJaOiN/VYASAciUAW2QId81WFkB+s67sjJcICzCXxv3+wEoAA/ujYkRhH9tTfevm7W7JtVUBMk5PD7bsuhEFuIg9Ee4KfM7IohkkFcVhRbqqaq0D8ML1PgAAA"
  },
  "pozhary-4": {
    "width": 2000,
    "height": 1335,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JZQAAUqFbcr4jsdhwAP7jQyJ01941PPSDOIe3m+XGIsghwAA="
  },
  "pozhary-5": {
    "width": 1335,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQBACdASoUAB4APuVepk2pJSOiN/VYASAciWMAwcwN2LsXB1jZ+TrS0y5IAP7o77Pbzc/TebNtnr94ZhoV5JJK2k1hpDogZA5DIT61JS7q8XPkVX6zNAAA"
  },
  "pozhary-6": {
    "width": 2000,
    "height": 1335,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JZQC2yB5aivAPKAD+6O/q74o2JjJ8xEmbReZMZHUJLu+PL5ywceH7HrAAAA=="
  },
  "rok-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwBACdASoUABsAPu1kq06ppaOiKA1RMB2JZgCdMxgBLKwnI4fpLMf/hxzD09ggAP7r/zxmTHAZVEh3OPAJpTXldJv+3r8n6tXyGmw57V3+TRsCvvtxriC5jbfAQMxAruwfDxixQrKKn9MhEaSq5Nv5yWtkB7or676m1i0AAAA="
  },
  "rok-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwBACdASoUABsAPuVgpE2pJaMiMAwBIByJaACdMyVIeC30+WZkFTiOrQCkVXvyJLAA/uvg7MdYdpVed0nVVV8befhrJ56QBitZ3BrnkT3nsAynt3GJkc225CTex+Vzh88+wMtTNngLxAt91hi9BN+k8xj2cNerQTONjQz5KiRi9P+pBgcAAA=="
  },
  "rok-3": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBgCdASoUACQAPtlWqE2oJKQiNVv8AQAbCWYAtvt1gKRIp16hu4aIickUH5o2RVizqzCnWjud0P70vToNY+0AAP7w1ck5+3XsfJamkiHdJmx5sPcMtvwSZWix/Ewcsya1dBvyLDLNm5TJl4lsPMWZ6SvzqU+a72uEyMSlF2v+7rGyFIF0WGr0JePqZawPB2T/0BqTAAA="
  },
  "rok-4": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwBACdASoUACQAPuFgpE2opaOmNVv4ARAcCUAVw4Qr+tV4vqYVZbfDjmMigoP03AAA/vKfO9FaLlKkSyTdKLSI5yEFLaMwlBB3XITYwfaoU6TbOK8wJWruIEj1C1ZqbyKgS0v50Ct6zh6KXAWsuh6kgZeAAA=="
  },
  "rok-5": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwBQCdASoUACQAPtVeok2oJaMiOrZoAQAaiWIAs4AWPhk68EqkxyVTJ/PdMe1ArPLsQPdrkl/VQAD+9CJOOZpjJK/5T4bvAobfdKjjSoXg3IQz9zI5ew/oe0ZNNIzzW+Ja6laHl2SxJFMRD+tg/OfcapQby51ta07rqHbwNIutD0BY9a32YAWI2/j5YhPKwPdxQdvup0g7kAAA"
  },
  "rozy-tsvety-10": {
    "width": 1766,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBQCdASoUABcAPuVeqE2pJSQiMAwBIByJaQAAW+vfyBDQuE7zXDJ29tREorKuoZsIgAD+6mehbZXKhOQyJya7qOsYYYkBAcT2vjqL4/hqTP7Eo8921n6Ajqli1PUHgphLt38JGqimAAAA"
  },
  "rozy-tsvety-11": {
    "width": 1794,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwBACdASoUABYAPu1urlIppiQiqAgBMB2JaQAAJSkZx3uhShkPeW19IsrDKQZoAM1oyRstWHenouSAE+MDb4E+MOsem0lc/kXTFcexULn8BQwgdpb/gHVc9sNdC1BJD+6U0wnAQoYwAAAA"
  },
  "rozy-tsvety-12": {
    "width": 1805,
    "height": 2000,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoUABYAPu1orE+ppiQiMBgIATAdiWkAACx6m2EsKUhZ2OvIdrCAAP7XJv0gSSSz5Z/o5Nfn9JI7sknK2AWV5UCsxwW+5gowY+n7tX6zjJtnr5n4n4AAAA=="
  },
  "rozy-tsvety-13": {
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JaACw7BjZrFg4k4PiRrAA/vK0MIU5GoICLEsI7hVnasMAlTyU3getRTNBXlHkEWWQ2DwqhLvrKTy4xBjKT9GpQYAAAA=="
  },
  "rozy-tsvety-14": {
    "width": 1280,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBQCdASoUAB4APu1irE4ppaSiKA1RMB2JbACdMoR1ZwGHg4+k+ZNY8HtLZerTK/3QBL7QAP74UL8WDPffvajKm+DM9z9yDczIktaTnNkpKGN0CxWS761kQZGJ/nEjpLHVo8Sbr7ZdP3L2sYHENbilGQSfMwPxOoXfnp68tsSCyqTfIrBk4xd0NmXGlw7PAtWAAA=="
  },
  "rozy-tsvety-15": {
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAA0APu1kq04ppaQiMAgBMB2JaQAAW6NfpLPvgfFgAP7O1n0vFSuEWT/IMlJX28BH39gb3JY3W8XStG1xRisxQ9fi+S1WAAA="
  },
  "rozy-tsvety-16": {
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoR4GBuXWscV9Y6asqAA/U1Nfltqwlv+JnCK8u0hLmDP2pzrYqqZRRfXd9iHSuXAt8OxY7RLU0SsrsaZCVv4AA=="
  },
  "rozy-tsvety-17": {
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAA0APu1mq04ppaQiMAgBMB2JaQAAUqq6d48m80DO2wAA/I8cHOgyRcbnJmBVLSlC5rTjihmMu3xHa2bxviEPYQXCgqUQT/c8vjAXFKAAAA=="
  },
  "rozy-tsvety-18": {
    "width": 1278,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwBACdASoUAB4APu1mqk2ppaQiMAgBMB2JaQDN/CDazrfHCGJ3wdSHXX4uol6kLkAA/s1xl4kmPqX6izBBht39vwhGj/7vod9fmwNLhQgroAHRb91VKzi8P5VJdrfRX8dDhFq01beFN0pPmexgAA=="
  },
  "rozy-tsvety-19": {
    "width": 960,
    "height": 1960,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBgCdASoUACkAPu1qrU8ppiQiKqoBMB2JZQDKABfROLqghgNr7mIufYH1OUm55ug0Q5GgD6N/Ex6b14AA/cSyZpC6fjoF2YA5itd2nDeNcRrvhT7m6pejXOHrgG8+yGvn9DXhIPMeCP/rfySF5k5awVn1EMkcwDA9O/OH+9xMxowx5YuH4ovH/sBD3plAYQZuIVOo4lDpGxWQAAA="
  },
  "rozy-tsvety-2": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBQCdASoUABsAPu1qq08ppiOiMBgIATAdiWkAAC5fuqXZYOajfx4RzX2ZDX5A7hYPYAAA/t7aYS//b2RcNnPTAl3KMtcqmd4ZuH2DyBxYQDQt+c+zbEkbG7kACozOl4UMyqMtgUODPgzJRS1Mf5iJv/CoULdWj3Sz30UtAU2AAA=="
  },
  "rozy-tsvety-20": {
    "width": 960,
    "height": 1903,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwBgCdASoUACgAPu1iqE2ppaQiNVgIATAdiWkAAD5M0kx0n0quJRI/kF/Hcv3WH/+BXIGyoF4YA1pbaKsvQAD+5xSi0vjIhqLIiSAtuMsnncvL4D7f5/jV5u0YfLX6ajjVPM1s1zMqCLDAxWAY9hM6WeR9O/irVbXCvh5EvobW30KaAzLsy+bqIMzzUoAA"
  },
  "rozy-tsvety-3": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUABsAPu1kqU2ppaOiMAgBMB2JaQAAW+vkwhttsqxxAAD+7UY7WGlCKz2fN61ENobv0+LzNhImg6WXdTazbnDQXuJ8TaOAAAA="
  },
  "rozy-tsvety-4": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASoUABsAPu1krE+ppSQiMBgIATAdiWkAAB/vskyRiKwEfL38QGgqTx9fEQQAAP6ZN13U1MyWSE/PPt/DTDp9kbo0E689a1LZWPc0MUUMI1/kmrPxY79hQnhs7BvVYfTEw5c6vV6ZsO5qazwEqEHInntZCWqHj/MXlfdANTQLMPiwkjsTeQAAAA=="
  },
  "rozy-tsvety-5": {
    "width": 1567,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQBACdASoUABoAPu1orVCppaQiqAqpMB2JaQAAJ9jbVM4a+vNike9i0j6udbumAADb0V2chLJ9vI7v2xDXEe8J/1ZKocasD4k1y+p6CAUJIy2GWZYXFqqI5jgHPdw01vo88zYuHhCtZem3pJrQen5WoLTQPNAjMAAAAA=="
  },
  "rozy-tsvety-6": {
    "width": 1610,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwBACdASoUABkAPulcqE2pJSQiN/VYASAdCWkAAC31yWr+AeHq/XKEfe3GUacTKuAA/up3ir2kan1bo93hxrWRo/pDDRLbWbU+Z6NEaXEaFdSt6+5F6fzv2GMXh+EdoCEH32xIMz/TgItZn3UiHGRS6YAAAA=="
  },
  "rozy-tsvety-7": {
    "width": 1666,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoUABgAPu1iq02ppaQiMBgMATAdiWkAAC502sLqlpJvcF+NiG9v8sFytgAA/ucolBclPdkCuL7WQgURZ6ft8UC+u4Nx70FR8VbOoHKI2CUoXPbtTPMp3gky/o0zyIEHw3emQ5zbYdCPDXkxVQncAAAA"
  },
  "rozy-tsvety-8": {
    "width": 1685,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQBACdASoUABgAPu1sqlEppaOiqAqpMB2JaQAAIXjeK7qeH0YrI0KPfhqef7vMAAD+5z8duwyYyPAWmA7VzKLozKrfQvqwTaKupe/Pnju5fPkcWja/EXMRIh6HEjUn3Uyu47wAAAA="
  },
  "rozy-tsvety-9": {
    "width": 1716,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwBACdASoUABcAPu1srFEppaQiqAqpMB2JaQAALjFec6gw+Jo8sfsrRq77AAD+302nsF0hn7LXNSCNp4AhElIS+RH/xZRz8Oo9KJzDvaHdAgLqqfShwuJYptDHDPDyx1wuoes26Ansq21gwAA="
  },
  "rus-1": {
    "width": 1539,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBQCdASoUABoAPu1urFEppqQiqAqpMB2JZQCdMxgBqfeOH0TZOuQvoSHdHhgA/qgAAP7xhBiNFBu0XnpPp15pCmKnbSV0lsbQ06lWvwrY5isHBODwDe3xLtiWdkdwj/Jg3d3BTy19qooCluxUAAAA"
  },
  "rus-2": {
    "width": 1559,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwBACdASoUABoAPu1kqU2ppaOiMAgBMB2JZQC4qCHgUcagCN5Y/JaqOrSMMvvTeAAA/vQk3JgqWQmagpYi58bJnb6IMdIEVwp77jq0WdM2aCA/IYbe3R322MAAAA=="
  },
  "rus-3": {
    "width": 1654,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQBACdASoUABgAPu1iqE4ppaOiMBgMATAdiWUAvdAQ791TY/DZc86pD6v08MAA/vQd1pcsEVsoka6dVLDwD8CjovA3Y85lMTZhBQOpaSeFk5fgAAA="
  },
  "rus-4": {
    "width": 960,
    "height": 1275,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBQCdASoUABsAPu1iq0+ppSOiMBgIATAdiWUAAC5l1ue4EgGQi+b/cSQ/QhaSbtbQAAD+9FAaa9wGm+dzKDIQDTyvE/4TvabaZwj96R1uqkL+BRzlJYKDaaE3akTZvbecfykbrbeyTDPGSfoylj3Rx2AAAA=="
  },
  "shah-i-mat-1": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBQCdASoUACQAPtlcpE2oJaOiOrZoAQAbCUAYH6mBDs6cF0fRaPQWwNDGsbHxApZHKlgA/vAJPQe24auU/Z2dPM804JXSAv/MI6j0MIPG/jh8Kse59Ujz3nj2o+IEeP/z/lNID3WwF+pHrIONFdAA"
  },
  "shardzha-1": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABwBACdASoUACQAPu1mqk6ppaOiKqwBMB2JZwDRCBZszegFHXXheN+qNKdgAAD+9CfuP1SyJGZs8yIAx/Oi5OsrTxZBq0zWup3pepO+XkEvfXRwcP5kAA=="
  },
  "silver-1": {
    "width": 1170,
    "height": 656,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoUAAsAPu1iqk2ppaQiMAgBMB2JQBdgA6ZXuVhQeb4qlu8AAM2ei88eqczGunTwGVYv0nyHFYHadY/LLD+He+D/Pj0RYAAA"
  },
  "silver-2": {
    "width": 1170,
    "height": 653,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYwCnFBbr3uXD+0pkdCoAAP7Ga6CFK0KPCFdzVurRmG0nqkW0wv38fYAAAA=="
  },
  "silver-3": {
    "width": 1170,
    "height": 647,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAAsAPu1kq04ppaQiMAgBMB2JZQC7ABjrgcnkcp9EgAD+VAO00cNN//mpO8gpmP4n4lF9QkGuARAA"
  },
  "silver-4": {
    "width": 1170,
    "height": 645,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAwCdASoUAAsAPu1kq04ppaQiMAgBMB2JZwDG9BdBsYXx84qO9pzAAPcGQjKp01QXGpcmNLL3H63QC/Qkl31QAAA="
  },
  "snezhnye-korolevy-1": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBgCdASoUACQAPu1mrk8ppaSiKrgMATAdiWMAvnuhxtegQZvm1ca9Krb5C8rX+DHMTt0/oIEsajIpaTAA/vkRGOe+QWe3p0Xg0cvty7SI+4fYtPPiQZT92KrRLRFPdcYQeKX5KkNF3yUYy/jC4VR+rwLRiXWHGFvu8pdp7N3ZkUrjE0xNifwUtBhAAA=="
  },
  "snezhnye-korolevy-2": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBQCdASoUACQAPuliqU2pJaQiKq35IB0JY12AWPGqcVzCqJksnZgNhZVeOquehXswwAAA/vXI+8mjfm9it/tMGe17lY19inr+pS2vsENvzao8nTmaKW42YBCjrd58YENr1nB+XvbAs8S/0etPQ+2TcoKjTjOqZWSFzPbUmqu1Qg1LjiznbrV9iOtJMfpvIpQWLIQrMxEA96wQAAA="
  },
  "snezhnye-korolevy-3": {
    "width": 960,
    "height": 1677,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBgCdASoUACMAPu1gqk8ppSOiNVQIATAdiUAUkAFh4iXOTF/+Jfxy9dTEwqPwkcvXKDs6rHqo/ZuMU7kAAP7Q7CaUi7x4581dz8VM+nojgloaJf7f6BdXSd2eeeJpZuNVDl/LGy+jy10qWM8ZcOF6m7Yrt2X45s7gZ8derGRYWEuwh+531Gns3/bsILPzgu4KTVQGfeN83FAA"
  },
  "snezhnye-korolevy-4": {
    "width": 960,
    "height": 1653,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBgCdASoUACIAPu1eq04ppKQiMBVdUTAdiWUAzNAubUG08nuWWc+mSTcLbBxiTvI9v35QSSqstSyAAP74UxiXfR+QcIemPo6yqv3CUvwU/G6m7thk7vYQB5UYORvIXO0pCMWm+cMv0KXRONFwCUYYoenxH74TohSL0OCSYwIAqEAwgMN6uERHqwTzdLAAAAAAAA=="
  },
  "tatu-1": {
    "width": 929,
    "height": 1641,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBgCdASoUACMAPu1iqU2ppaOiMBVdUTAdiWMAsOwKGnZijzf8HdPTwWI7euQe3FV2p06RPHu1Q8uAAP7o8DjQtAHGrW8gnrcMpDCPaV11xsy+sQNc1zPZ9MbiB2RH4QMtTwfKqfN4Dh6HnHoytS48Hi/p91O2z8sIF+hpXFRQwarCJR5keOX6FdLkAfcoAAA="
  },
  "tsirk-1": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBACdASoUABsAPu1oqk8ppiOiMBgIATAdiUAToAG0+OKYMvQs8lwfJ9ZQAP7awqxYq1EvjwZOf08WdAt0L3qPRRR9Spy3Rumb784bspD2sbGIJ3jTy4kQk8NekS+MI3bObZVjnWopvUr5NkDaXvGY8ilhgAAA"
  },
  "tsirk-2": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACwBQCdASoUABsAPuFcqU2opSQiMAwBEBwJbACxHuOCmCksdTvO7S5zdOdRfPPUQDpf8knaAoAA/tEHM/jaZmWU7XqQxdaG4a5nkp+kZQIF1TqXWmOayVklMIK0SMu2K/gYma0ZfX+StoG/4zBBTxd3BtKK+K1XG93bc9ZShyKZDG0/BjL25IO/CCDDpT72rZAAAA=="
  },
  "tsirk-3": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQBACdASoUABsAPuVcpE2pJSOiMAwBIByJaACdACHOlKATONUuD3EKgOlPrxGNKAD+zO0zXIcHMSDoXP/dMTkwQkSrGQjDRnbLVgruF9ktbAJK3YXKSqoKudXoxksyjc4XNmD835aiBpCMh0HKVnkF4AA="
  },
  "venom-vumen-1": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwBACdASoUABsAPu1kqU2ppaOiMAgBMB2JZQDI1CHez/D48X4r3wsz3DpKXmFAAP7yyahei1HxxR+1y/EV2Yp960yVMCNQlr3shwy8ZiKHQhereUj8sVtMrmfPg4IakSy7A7v+7gAAAA=="
  },
  "venom-vumen-2": {
    "width": 1333,
    "height": 2000,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwBACdASoUAB4APuVip02pJiOiMAwBIByJZgCw7CHEn0ElXn0+ZdkB+HrVNS2AAP7ugg/FtB5RVJDVDtvxcJqn9tu/XpXbJPy33w/C17mf63mDKiNGTBcP1TxXbwVF37CaZCa6bNeziO6in3dE8AAA"
  },
  "venom-vumen-3": {
    "width": 1064,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQBQCdASoUACYAPu1eqE8ppKOiMBVdUTAdiWQAnTNHSIATUOOcZGhMfyNV4mJuRQq1Wx0XEigAAP7vXJ/tM3tr8mRkU2wugjmNschL/JZ/y+mCBUmBfCU3HJ/rg2ND5zPzxiknEWOeCzTKSvF9KFc7e9Qc62AS/njLxTBBYNoSPvrqur7CSpGcumJI6cAA"
  },
  "yelloustoun-1": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoUACQAPu1qqE8ppiOiKqwBMB2JYwC2yBG7Tv9g1Ey2udH0qz+DlX3hfE3c9jSwAPZqT5VRUJ/XmzvJlnVgqlvVwh0IYsmPPaBdqivOD8dBv6bXT7ej8XsEXoDPMNoq7P2WFEmk1FwCjLkwLfJtlTMzDJ69uDOx+h9Ej4WE4AGWYAAA"
  },
  "yelloustoun-2": {
    "width": 1125,
    "height": 2000,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBQCdASoUACQAPuloqk2pJqQiMBqqqSAdCUAVHoL6ubN+9lTL/WJ+WCYc1kUDJr0AuMAA/IvWrtZEQ6jb8j10WKJVp3Mk8Foj36/95UOfCcPl1FamyYZbLg9j6Wr/8XxcNr8DPUKVWIpXZsTOuSViwkafXCHUWivgmyAA"
  },
  "yelloustoun-3": {
    "width": 1440,
    "height": 1920,
    "widths": [
      480,
      768,
      1200
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQBACdASoUABsAPu1mqk+ppSOiMBgIATAdiUATpmHQIx3INpGDZGA63kwH1Ndn6ACQDcoO2nPU+404evWudYWPA6Y3OZCgjPC7afTiR+9oVLDcbsZDUq3Ib5Dco3FKMEzEXr4wAAA="
  },
  "yelloustoun-4": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBQCdASoUABsAPu1sqk+ppiOiMBgIATAdiWMAs4AQ8CGN6Yxp7YAx0yPVv22KM9HAAAD+8NY9eYyeRdgCzqeqSnekJv1IBvH4XtkTGGaNkUtNGjgko8ArP/yq/W5etRxHTD4WVVIRFeAtBh9pNoGz+cwG+veoAAA="
  },
  "yelloustoun-5": {
    "width": 1086,
    "height": 1448,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwBACdASoUABsAPuVgp02pJaOiMAwBIByJYwDLpCHfwTgSQVFAZakYEdQr32AAAP71ZWKLMFX1y7zshzyPGWBhZDrOeNOXkYurYmKBQiyBgAAA"
  },
  "zov-vorona-1": {
    "width": 960,
    "height": 525,
    "widths": [
      480,
      768
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoUAAsAPu1kqk4ppaQiMAgBMB2JY2HgTKATj0cqSDAAAP7wjIetz4m2Xqz8odgCWoiGLDj8LoY3AbgA"
  }
} as const satisfies Record<string, MediaEntry>;

export type MediaSlug = keyof typeof MEDIA_MANIFEST;
