import type { MediaSlug } from './media.generated';

/**
 * One repertoire piece. Every show gets its own route at /shows/[slug], so the
 * fields here drive both the catalogue tile and the full show page.
 *
 * Titles and groupings come from the studio's own archive — the folder names
 * under НОМЕРА. Descriptions stay close to what the photographs actually show
 * (costume, palette, staging); nothing about audience numbers, dates or
 * awards is asserted here unless a source document confirms it.
 */
export type Show = {
  slug: string;
  title: string;
  /** Latin/secondary line used in the oversized display typography. */
  latin: string;
  category: ShowCategory;
  /** One-line hook, shown on the catalogue tile. */
  tagline: string;
  /** Editorial lead paragraph on the show page. */
  intro: string;
  palette: [string, string];
  cover: MediaSlug;
  /** Extra photographs shown in the show page's own gallery strip. */
  stills: MediaSlug[];
  costume: string;
  /** True where the archive holds only video, so the cover is a video still. */
  coverFromVideo?: boolean;
  /** Marks the pieces that lead the home page's featured grid. */
  featured?: boolean;
  /** Wider tile in the catalogue mosaic. */
  wide?: boolean;
};

export type ShowCategory = 'show' | 'fashion' | 'folk' | 'classic' | 'ny' | 'tribute';

export const SHOW_CATEGORIES: { id: ShowCategory | 'all'; label: string }[] = [
  { id: 'all', label: 'Все' },
  { id: 'show', label: 'Шоу-программы' },
  { id: 'fashion', label: 'Fashion' },
  { id: 'tribute', label: 'Трибьюты' },
  { id: 'ny', label: 'Новый год' },
  { id: 'folk', label: 'Фолк' },
  { id: 'classic', label: 'Классика' },
];

export const CATEGORY_LABEL: Record<ShowCategory, string> = {
  show: 'Шоу-программа',
  fashion: 'Fashion',
  folk: 'Фолк',
  classic: 'Классика',
  ny: 'Новый год',
  tribute: 'Трибьют',
};

export const SHOWS: Show[] = [
  {
    slug: 'rozy-tsvety',
    title: 'РОЗЫ ЦВЕТЫ',
    latin: 'ROSES',
    category: 'fashion',
    tagline: 'Чёрно-белая флористика',
    intro:
      'Графичный номер почти без цвета: широкие поля шляп, объёмные цветочные формы и свет, который лепит силуэт.',
    palette: ['#0a0a0c', '#7c1f2e'],
    cover: 'rozy-tsvety-13',
    stills: ['rozy-tsvety-2', 'rozy-tsvety-3', 'rozy-tsvety-5', 'rozy-tsvety-8', 'rozy-tsvety-11'],
    costume: 'Крупные шляпы, объёмные цветы, чёрно-белая палитра.',
    featured: true,
    wide: true,
  },
  {
    slug: 'matritsa',
    title: 'МАТРИЦА',
    latin: 'MATRIX',
    category: 'show',
    tagline: 'Кожа, дым и силуэты',
    intro:
      'Кожаные тренчи, тёмные очки и синхрон, отточенный до одного силуэта — самый узнаваемый номер репертуара.',
    palette: ['#07090a', '#1f6f57'],
    cover: 'matritsa-9',
    stills: ['matritsa-1', 'matritsa-5', 'matritsa-8', 'matritsa-3'],
    costume: 'Кожаные тренчи, чёрные очки, короткие тёмные парики.',
    featured: true,
  },
  {
    slug: 'snezhnye-korolevy',
    title: 'СНЕЖНЫЕ КОРОЛЕВЫ',
    latin: 'SNOW QUEENS',
    category: 'ny',
    tagline: 'Короны, кристаллы, глиттер',
    intro:
      'Ледяная белизна, кристаллы на коже и короны — номер рассчитан на тёмную сцену и контровой свет.',
    palette: ['#0b0b10', '#a9b8d6'],
    cover: 'snezhnye-korolevy-2',
    stills: ['snezhnye-korolevy-1', 'snezhnye-korolevy-3', 'snezhnye-korolevy-4'],
    costume: 'Короны, кристаллы, глиттер, белые корсеты.',
    featured: true,
  },
  {
    slug: 'apalle',
    title: 'АПАЛЛЕ',
    latin: 'APALLE',
    category: 'fashion',
    tagline: 'Латекс и красные рюши',
    intro:
      'Fashion-выход на грани подиума и перформанса: чёрный латекс, алая органза и подача, рассчитанная на камеру.',
    palette: ['#0a0708', '#c8102e'],
    cover: 'apalle-3',
    stills: ['apalle-1', 'apalle-2', 'apalle-4', 'apalle-5'],
    costume: 'Латексные платья, объёмные рюши из органзы, длинные перчатки.',
    featured: true,
    wide: true,
  },
  {
    slug: 'aziya',
    title: 'АЗИЯ',
    latin: 'ASIA',
    category: 'show',
    tagline: 'Алый шёлк и веера',
    intro:
      'Самая большая фотосессия архива: красный шёлк, цветочные головные уборы, веера и восточная пластика.',
    palette: ['#0c0607', '#b3202f'],
    cover: 'aziya-3',
    stills: ['aziya-4', 'aziya-6', 'aziya-9', 'aziya-14', 'aziya-18'],
    costume: 'Шёлковые кимоно, цветочные уборы, веера.',
    featured: true,
  },
  {
    slug: 'gretsiya',
    title: 'ГРЕЦИЯ',
    latin: 'GREECE',
    category: 'show',
    tagline: 'Белое с золотом',
    intro:
      'Античные драпировки, золотые пояса и веера. Номер с самым большим видеоархивом — снимался чаще других.',
    palette: ['#0b0a08', '#e6cfa8'],
    cover: 'gretsiya-10',
    stills: ['gretsiya-1', 'gretsiya-3', 'gretsiya-5', 'gretsiya-8', 'gretsiya-12'],
    costume: 'Белые драпировки, золотые пояса и украшения, кружевные веера.',
    featured: true,
  },
  {
    slug: 'barokko',
    title: 'БАРОККО',
    latin: 'BAROQUE',
    category: 'classic',
    tagline: 'Пудра, кружево, чёрно-белое',
    intro:
      'Барочная эстетика в графике без цвета: пудреные парики, корсеты, кружево и тяжёлый сценический свет.',
    palette: ['#0a0a0c', '#d8d3cb'],
    cover: 'barokko-6',
    stills: ['barokko-1', 'barokko-2', 'barokko-4', 'barokko-8', 'barokko-10'],
    costume: 'Пудреные парики, корсеты, кружево, чёрно-белая палитра.',
  },
  {
    slug: 'gladiatory',
    title: 'ГЛАДИАТОРЫ',
    latin: 'GLADIATORS',
    category: 'show',
    tagline: 'Красное с золотом, перья',
    intro: 'Тяжёлый декоративный номер: золотой орнамент, алые перья, скульптурные головные уборы.',
    palette: ['#0c0606', '#c9761f'],
    cover: 'gladiatory-1',
    stills: ['gladiatory-2', 'gladiatory-3', 'gladiatory-4'],
    costume: 'Золотой орнамент, красные перья, корсеты с декором.',
  },
  {
    slug: 'bogini',
    title: 'БОГИНИ',
    latin: 'GODDESSES',
    category: 'show',
    tagline: 'Золото и солнечные короны',
    intro: 'Золотые костюмы и лучевые головные уборы — светлый, парадный номер для больших сцен.',
    palette: ['#0b0a07', '#d9b98a'],
    cover: 'bogini-1',
    stills: ['bogini-2', 'bogini-3', 'bogini-4', 'bogini-5'],
    costume: 'Золотые костюмы с вышивкой, короны-лучи.',
  },
  {
    slug: 'pozhary',
    title: 'ПОЖАРЫ',
    latin: 'FIRES',
    category: 'show',
    tagline: 'Красный бархат и розы',
    intro:
      'Драматичный номер с мужской партией: красный бархат, розы в волосах, глубокие тени.',
    palette: ['#0a0708', '#a51e2d'],
    cover: 'pozhary-1',
    stills: ['pozhary-2', 'pozhary-3', 'pozhary-4', 'pozhary-5', 'pozhary-6'],
    costume: 'Красный бархат и пиджаки, кружево, цветы в причёсках.',
  },
  {
    slug: 'kombinatsiya',
    title: 'КОМБИНАЦИЯ',
    latin: 'KOMBINATSIYA',
    category: 'tribute',
    tagline: 'Мех и синий атлас',
    intro:
      'Ретро-трибьют: белые меховые шапки, синие колготки, ковёр на стене — узнаваемая эстетика позднего СССР.',
    palette: ['#0b0910', '#2b37d6'],
    cover: 'kombinatsiya-9',
    stills: ['kombinatsiya-1', 'kombinatsiya-3', 'kombinatsiya-5', 'kombinatsiya-7'],
    costume: 'Меховые шапки и шубы, синий атлас, яркий грим.',
  },
  {
    slug: 'maykl-dzhekson',
    title: 'МАЙКЛ ДЖЕКСОН',
    latin: 'MICHAEL JACKSON',
    category: 'tribute',
    tagline: 'Синие костюмы в полоску',
    intro: 'Трибьют-номер: костюмы в полоску, широкополые шляпы, узнаваемая пластика.',
    palette: ['#08090f', '#2f5fd0'],
    cover: 'maykl-dzhekson-1',
    stills: ['maykl-dzhekson-2', 'maykl-dzhekson-3', 'maykl-dzhekson-5', 'maykl-dzhekson-7'],
    costume: 'Синие костюмы в полоску со стразами, шляпы, белые перчатки.',
  },
  {
    slug: 'novyy-god',
    title: 'НОВЫЙ ГОД',
    latin: 'NEW YEAR',
    category: 'ny',
    tagline: 'Красный, сцена, финал',
    intro: 'Основной номер декабрьского репертуара: красные костюмы, открытая подача, работа с залом.',
    palette: ['#0b0708', '#b3202f'],
    cover: 'novyy-god-2',
    stills: ['novyy-god-1', 'novyy-god-3', 'novyy-god-5', 'novyy-god-7'],
    costume: 'Красные костюмы и корсеты, мех, головные уборы.',
  },
  {
    slug: 'tsirk',
    title: 'ЦИРК',
    latin: 'CIRCUS',
    category: 'show',
    tagline: 'Перья, полоска, шары',
    intro: 'Яркий праздничный номер: красные перья, полосатые костюмы, декорации из шаров и карт.',
    palette: ['#0c0708', '#c8102e'],
    cover: 'tsirk-1',
    stills: ['tsirk-2', 'tsirk-3'],
    costume: 'Красные перья, полосатые колготки, цирковые головные уборы.',
  },
  {
    slug: 'rus',
    title: 'РУСЬ',
    latin: 'RUS',
    category: 'folk',
    tagline: 'Хохлома и кокошники',
    intro: 'Фолк-номер: хохломской орнамент, кокошники, красно-золотая палитра и современная пластика.',
    palette: ['#0c0705', '#c9761f'],
    cover: 'rus-1',
    stills: ['rus-2', 'rus-3', 'rus-4'],
    costume: 'Кокошники, хохломской орнамент, кожаные перчатки.',
  },
  {
    slug: 'getsbi',
    title: 'ГЭТСБИ',
    latin: 'GATSBY',
    category: 'show',
    tagline: 'Двадцатые, пайетки, мундштуки',
    intro: 'Номер в эстетике ар-деко: пайетки, длинные перчатки, жемчуг и мундштуки.',
    palette: ['#0b0a09', '#d9b98a'],
    cover: 'getsbi-1',
    stills: [],
    costume: 'Платья с бахромой и пайетками, длинные перчатки, жемчуг.',
  },
  {
    slug: 'yelloustoun',
    title: 'ЙЕЛЛОУСТОУН',
    latin: 'YELLOWSTONE',
    category: 'show',
    tagline: 'Вестерн',
    intro: 'Ковбойские шляпы, банданы, замша — вестерн-номер с прямой, открытой подачей.',
    palette: ['#0b0908', '#a8763f'],
    cover: 'yelloustoun-1',
    stills: ['yelloustoun-2', 'yelloustoun-3', 'yelloustoun-4', 'yelloustoun-5'],
    costume: 'Ковбойские шляпы, банданы, замша и бахрома.',
  },
  {
    slug: 'dikie-zemli',
    title: 'ДИКИЕ ЗЕМЛИ',
    latin: 'WILD LANDS',
    category: 'show',
    tagline: 'Перья и карнавальная пластика',
    intro:
      'Карнавальный номер с крупными перьевыми уборами — один из самых узнаваемых кадров архива.',
    palette: ['#0a0908', '#b98a4a'],
    cover: 'dikie-zemli-4',
    stills: ['dikie-zemli-1', 'dikie-zemli-2', 'dikie-zemli-3', 'dikie-zemli-5'],
    costume: 'Перьевые головные уборы, кожа, цепи, украшения.',
  },
  {
    slug: 'nimfy',
    title: 'НИМФЫ',
    latin: 'NYMPHS',
    category: 'show',
    tagline: 'Зелёный шёлк',
    intro: 'Пластический номер в зелёном шёлке — построен на текучести ткани и медленной амплитуде.',
    palette: ['#070b08', '#3f8f52'],
    cover: 'nimfy-1',
    stills: [],
    costume: 'Зелёный шёлк, драпировки, золотые пояса.',
  },
  {
    slug: 'zov-vorona',
    title: 'ЗОВ ВОРОНА',
    latin: 'RAVEN CALL',
    category: 'show',
    tagline: 'Чёрные перья, красный свет',
    intro: 'Тёмный номер с крупными перьевыми конструкциями и красной заливкой сцены.',
    palette: ['#08080a', '#8f1b26'],
    cover: 'zov-vorona-1',
    stills: [],
    costume: 'Чёрные перья, объёмные крылья, тёмный грим.',
  },
  {
    slug: 'feniks',
    title: 'ФЕНИКС',
    latin: 'PHOENIX',
    category: 'show',
    tagline: 'Алый атлас и золотые перья',
    intro: 'Красные атласные платья и золотые перьевые накидки на тёмной сцене.',
    palette: ['#0a0607', '#c8102e'],
    cover: 'feniks-1',
    stills: ['feniks-2'],
    costume: 'Алые атласные платья, золотые перьевые накидки.',
  },
  {
    slug: 'silver',
    title: 'СИЛЬВЕР',
    latin: 'SILVER',
    category: 'fashion',
    tagline: 'Кристальные короны',
    intro: 'Крупный план и металл: кристальные короны-лучи, серебро, зеркальные фактуры.',
    palette: ['#090a0c', '#b9c3d1'],
    cover: 'silver-1',
    stills: ['silver-2', 'silver-3', 'silver-4'],
    costume: 'Кристальные короны, серебро, зеркальные ткани.',
  },
  {
    slug: 'venom-vumen',
    title: 'ВЕНОМ ВУМЕН',
    latin: 'VENOM WOMEN',
    category: 'fashion',
    tagline: 'Чёрный латекс',
    intro: 'Ночной номер в чёрном латексе — прямая, жёсткая подача.',
    palette: ['#08080a', '#4a4f5a'],
    cover: 'venom-vumen-1',
    stills: ['venom-vumen-2', 'venom-vumen-3'],
    costume: 'Латекс, кожа, тёмный грим.',
  },
  {
    slug: 'gaga',
    title: 'ГАГА',
    latin: 'GAGA',
    category: 'fashion',
    tagline: 'Изумруд и шляпы',
    intro: 'Изумрудно-зелёные костюмы, широкополые шляпы и тёмные очки.',
    palette: ['#06100b', '#1f7a55'],
    cover: 'gaga-1',
    stills: ['gaga-2', 'gaga-3'],
    costume: 'Зелёные костюмы с блеском, шляпы, длинные перчатки.',
  },
  {
    slug: 'otel',
    title: 'ОТЕЛЬ',
    latin: 'HOTEL',
    category: 'show',
    tagline: 'Красные рюши и портье',
    intro: 'Сюжетный номер с мужской партией: красные рюши, форма портье, гостиничная сценография.',
    palette: ['#0a0607', '#b3202f'],
    cover: 'otel-1',
    stills: ['otel-2', 'otel-3', 'otel-4', 'otel-5'],
    costume: 'Красные рюши и колготки, форма портье, шляпки.',
  },
  {
    slug: 'rok',
    title: 'РОК',
    latin: 'ROCK',
    category: 'show',
    tagline: 'Кожа и электрогитары',
    intro: 'Рок-номер с прямой, жёсткой пластикой и соответствующей сценографией.',
    palette: ['#0a0a0c', '#8a2b32'],
    cover: 'rok-1',
    stills: ['rok-2', 'rok-3', 'rok-4', 'rok-5'],
    costume: 'Кожа, заклёпки, сетка, тёмный грим.',
  },
  {
    slug: 'disko',
    title: 'ДИСКО',
    latin: 'DISCO',
    category: 'show',
    tagline: 'Блеск и бахрома',
    intro: 'Дискотечный номер: блестящие костюмы, бахрома, работа с вокалистом.',
    palette: ['#0a0a10', '#3f6fd0'],
    cover: 'disko-2',
    stills: ['disko-1'],
    costume: 'Блестящие костюмы с бахромой, украшения, высокие сапоги.',
  },
  {
    slug: 'tatu',
    title: 'ТАТУ',
    latin: 'T.A.T.U.',
    category: 'tribute',
    tagline: 'Клетчатые юбки и галстуки',
    intro: 'Трибьют начала двухтысячных: клетчатые юбки, белые рубашки, галстуки.',
    palette: ['#0a0a0c', '#9a2530'],
    cover: 'tatu-1',
    stills: [],
    costume: 'Клетчатые юбки, белые рубашки, галстуки.',
  },
  {
    slug: 'alisa-v-strane-chudes',
    title: 'АЛИСА В СТРАНЕ ЧУДЕС',
    latin: 'ALICE',
    category: 'show',
    tagline: 'Сказочные персонажи',
    intro: 'Костюмированный номер по мотивам сказки: Алиса, Червонная Королева, Шляпник.',
    palette: ['#0a0810', '#7c1f2e'],
    cover: 'alisa-v-strane-chudes-1',
    stills: ['alisa-v-strane-chudes-2'],
    costume: 'Голубое платье Алисы, костюм Червонной Королевы, Шляпник.',
  },
  {
    slug: 'bal-anastasiya',
    title: 'БАЛ АНАСТАСИЯ',
    latin: 'ANASTASIA BALL',
    category: 'classic',
    tagline: 'Бордовый бархат',
    intro: 'Бальный номер в бордовом бархате — камерный, с акцентом на парную работу.',
    palette: ['#0a0708', '#6e1a28'],
    cover: 'bal-anastasiya-1',
    stills: ['bal-anastasiya-2'],
    costume: 'Бордовый бархат, длинные перчатки, украшения.',
  },
  {
    slug: 'ofishl',
    title: 'ОФИШЛ',
    latin: 'OFFICIAL',
    category: 'show',
    tagline: 'Костюмы и очки',
    intro: 'Строгий номер: костюмы, галстуки, тёмные очки, минимум декора.',
    palette: ['#08080a', '#5a6070'],
    cover: 'ofishl-1',
    stills: ['ofishl-2'],
    costume: 'Классические костюмы, галстуки, тёмные очки.',
  },
  {
    slug: 'iskusstvo',
    title: 'ИСКУССТВО',
    latin: 'ART',
    category: 'show',
    tagline: 'Сборная программа в четырёх частях',
    intro:
      'Не отдельный номер, а собранная программа: хип-хоп-старт, классическая часть, дуэты и общий финал. Постановка — Егор и Анастасия Бондаревы.',
    palette: ['#0a0a0c', '#8a6b3f'],
    cover: 'iskusstvo-1',
    stills: [],
    costume: 'Синие брюки и пиджаки у парней, белые платья у девушек.',
  },
  {
    slug: 'balerina-shou-balet',
    title: 'БАЛЕРИНА + ШОУ-БАЛЕТ',
    latin: 'BALLERINA',
    category: 'classic',
    tagline: 'Классика и шоу-балет',
    intro: 'Академический выход балерины в сочетании с шоу-балетом.',
    palette: ['#0a0a0d', '#dfe3ea'],
    cover: 'balerina-shou-balet-1',
    stills: [],
    costume: 'Классическая пачка, пуанты.',
  },
  {
    slug: 'kabare',
    title: 'КАБАРЕ',
    latin: 'CABARET',
    category: 'show',
    tagline: 'Красные перья и вокал',
    intro: 'Кабаре-программа с живым вокалом: красные перьевые веера, корсеты, работа на публику.',
    palette: ['#0a0608', '#b3202f'],
    cover: 'kabare-1',
    stills: [],
    costume: 'Красные корсеты, перьевые веера, чулки.',
    coverFromVideo: true,
  },
  {
    slug: 'pakahontas',
    title: 'ПАКАХОНТАС',
    latin: 'POCAHONTAS',
    category: 'show',
    tagline: 'Этника и бахрома',
    intro: 'Этнический номер с крупными украшениями и бахромой.',
    palette: ['#0a0708', '#a8465a'],
    cover: 'pakahontas-1',
    stills: [],
    costume: 'Кожа с бахромой, массивные украшения, перья.',
    coverFromVideo: true,
  },
  {
    slug: 'fil-gud',
    title: 'ФИЛ ГУД',
    latin: 'FEEL GOOD',
    category: 'fashion',
    tagline: 'Неон и бахрома',
    intro: 'Номер в неоновом свете: облегающие костюмы с бахромой, световые штативы на сцене.',
    palette: ['#0d0710', '#c0339a'],
    cover: 'fil-gud-1',
    stills: [],
    costume: 'Облегающие костюмы с бахромой.',
    coverFromVideo: true,
  },
  {
    slug: 'shardzha',
    title: 'ШАРДЖА',
    latin: 'SHARJAH',
    category: 'show',
    tagline: 'Восточная программа',
    intro: 'Программа с восточной пластикой: чёрные костюмы, серебряные головные уборы с подвесками.',
    palette: ['#08080a', '#b08d4a'],
    cover: 'shardzha-1',
    stills: [],
    costume: 'Чёрные костюмы, серебряные уборы с подвесками, широкие браслеты.',
    coverFromVideo: true,
  },
  {
    slug: 'shah-i-mat',
    title: 'ШАХ И МАТ',
    latin: 'CHECKMATE',
    category: 'show',
    tagline: 'Клубный формат',
    intro: 'Номер для клубных площадок — снят в живой обстановке зала.',
    palette: ['#08080a', '#5f6a7a'],
    cover: 'shah-i-mat-1',
    stills: [],
    costume: 'Чёрно-белая палитра.',
    coverFromVideo: true,
  },
  {
    slug: 'ironiya-sudby',
    title: 'ИРОНИЯ СУДЬБЫ',
    latin: 'NEW YEAR STORY',
    category: 'ny',
    tagline: 'Новогодняя постановка для зала',
    intro: 'Сюжетная новогодняя программа для банкетного зала — с декорациями и работой на публику.',
    palette: ['#0a0808', '#a8763f'],
    cover: 'ironiya-sudby-1',
    stills: [],
    costume: 'Новогодняя сценография и костюмы под сюжет.',
    coverFromVideo: true,
  },
];

export const getShow = (slug: string) => SHOWS.find((s) => s.slug === slug);
export const FEATURED_SHOWS = SHOWS.filter((s) => s.featured);
